### ISSUE TITLE
Angular Typescript snippet for "Controller" is not correct

### ISSUE THREAD

**Issue by chintans** [ligershark/side-waffle#102]
Please refer to this link of StackOverflow for explanation of my issue

http://stackoverflow.com/questions/21692713/unable-to-use-services-injected-from-constructor-in-methods-in-typescript-using

the issue is that methods extended on a class are not able to access this scope for execution.

**Comment by kentcooper** [comment]
This was not a problem with the template itself. This was caused by the way typescript handles "this". This can be closed.
