### ISSUE TITLE
Building with VS2013

### ISSUE THREAD

**Issue by MarkStega** [ligershark/side-waffle#120]
I cloned the repository and tried to build (vs2013.U2CTP2 and VS2013 SDK). The build failed on the project "templatepack" when trying to reference "Microsoft.VisualStudio.Shell.11.0". I removed that reference and added references to "Microsoft.VisualStudio.Shell.12.0", "Microsoft.VisualStudio.Shell.Immutable.12.0", and "Microsoft.VisualStudio.Shell.Interop.12.0". The build now succeeds

Is this simply because I don't have VS2012 installed on this workstation?

**Comment by RandomlyKnighted** [comment]
The current build of SideWaffle should build with any version of Visual Studio. If you continue to have problems please reopen with additional details.
