### ISSUE TITLE
Add support for a NuBuild-like project template...

### ISSUE THREAD

**Issue by dbuckingham** [ligershark/side-waffle#121]
Please consider adding support for a [NuBuild](http://visualstudiogallery.msdn.microsoft.com/3efbfdea-7d51-4d45-a954-74a2df51c5d0)-like project template.

This new project template would allow developers to build NuGet packages inside of Visual Studio, without the need to create custom MSBuild/psake scripts and/or batch files.

This project template would specifically allow the user to add references to DLLs, project references, and NuGet packages.  Once built, the necessary dependencies and references could be compiled into the .nuspec file.

Additionally, it would be great to support building a package using the [convention based working directory](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#From_a_convention_based_working_directory) approach.  This would allow developers the ability to add a readme.txt file, content files (such as config transforms, javascript/css, etc.), and the various PowerShell scripts (init, install, uninstall, etc.) necessary to carefully craft a NuGet package.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I don't know how to do this, but I'm definitely interested in learning once the dynamic templates feature has been fully implemented.

**Comment by sayedihashimi** [comment]
In VS2015 I'm hoping that there will be a first class way to make a NuGet package for most project types. We already have ASP.NET 5 projects which create NuGet packages so I'm not sure if this is needed.

What I'd recommend now is that NuBuild team to create project templates (if they haven't already) and ship that with their vsix.

**Comment by RandomlyKnighted** [comment]
Since the current recommendation is to get the NuBuild team to get the NuBuild team to ship project creation in their VSIX and there will (hopefully) be a way to do this via VS2015 I'm going to go ahead and close this.
