### ISSUE TITLE
Create a Web Pages (Razor v3) template

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#132]
We should create a C# Web Application Project template for Razor v3. It should be based on the Razor v3 website template in VS today.

**Comment by RandomlyKnighted** [comment]
I've was able to create a Razor v3 website and converted it to a WAP. I hope to replicate this in the SideWaffle project and have a PR soon with the new template.

**Comment by RandomlyKnighted** [comment]
This was added and merged on 5/9/2015.
