### ISSUE TITLE
Update Add Template Ref to drop files into target project

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#161]
When adding a ```TemplateReference``` there are two steps today.
 1. Invoke Add Template Reference menu option
 1. Add SideWaffle Project Template files into the target project

We should try and avoid the second step by having the VS tooling to add the files into the target project if they are not already there.

**Comment by RandomlyKnighted** [comment]
Closing due to it being an almost identical issue to #238 (238 requests a third step be removed from the process i.e. importing the TemplateBuilder package)
