### ISSUE TITLE
Cloud-based SideWaffle

### ISSUE THREAD

**Issue by cH40z-Lord** [ligershark/side-waffle#166]
Hey there,

I've been using SideWaffle for quite a while and it's been purely awesome! Good job!

Like the title already suggests I was thinking about moving SideWaffle to the cloud. The idea here was that you no longer need to release a new version of the SideWaffle VS extension if you've made some changes to (existing) templates. Instead, you just upload your new templates to the cloud (maybe even with a stable and beta/preview "branch") which then gets synced by the VS extension.

One thing I need to point out here is that I no idea if this is possible with the current VS SDK to add or modify templates on the fly while VS is running. But if it's possible that would be pretty neat to have an extension that (automatically?) updates itself when VS starts or manually triggered by the user.

If this has been already proposed then please ignore me, I might have missed that :)
Otherwise, what do you think?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi was going back through this to see where we are in relation to our original plan. Did we ever work through the issue of not being able to extract SideWaffle until a project is created? 

Also are we still planning to add an editor for templatesources.json at some point? 

Other than that it looks like this first release will pretty well include all the key points mentioned here.

**Comment by sayedihashimi** [comment]
>@sayedihashimi was going back through this to see where we are in relation to our original plan. Did we ever work through the issue of not being able to extract SideWaffle until a project is created? 

yeah fixed that

>Also are we still planning to add an editor for templatesources.json at some point? 

@madskristensen can u create a json schema for https://github.com/ligershark/side-waffle/blob/autoupdate/TemplatePack/templatesources.json and add to http://schemastore.com?

>Other than that it looks like this first release will pretty well include all the key points mentioned here.

@RandomlyKnighted agreed, can we add the wiki doc on autoupdate and then close this item with a link to a build to try it?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi yeah, once I get that finish adding that bug fix we talked about and you've approved the PR I can take care of the wiki doc and the link.

**Comment by RandomlyKnighted** [comment]
The first build and instructions for the dynamic templates version of SideWaffle can be [found here[(https://github.com/ligershark/side-waffle/wiki/Dynamic-templates).
