### ISSUE TITLE
Provide Change Log

### ISSUE THREAD

**Issue by MaximRouiller** [ligershark/side-waffle#174]
This is a two part issue. 

First, before actually deploying anything, we should compile a list of things that have changed (bug fixes, new templates, who framed Roger Rabbit, etc.).

Then, push those actual changes to the website where we can see them with the version number.

As an example... I just received an update for SideWaffle today. My question is... "wait! there's new templates!? I wanna try!!" So go to SideWaffle.com and see the massive list of templates (props on the quantity) but no way of knowing what's new.

![image](https://cloud.githubusercontent.com/assets/209384/4154964/232059f6-3466-11e4-9490-9fcc0e8caf3d.png)

**Comment by RandomlyKnighted** [comment]
@sayedihashimi we should probably update SideWaffle with the release notes from the website that I did..that way when people update it they are changing the version that will be released

**Comment by sayedihashimi** [comment]
I agree, @madskristensen did you have a chance to review Tyler's PR to the SideWaffle website? If so can you publish it?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi the PR was approved on the SideWaffle website a while back. Can we update the existing release notes so that when people make changes they are updating the one that will be used on the website?

**Comment by RandomlyKnighted** [comment]
I believe it's safe to say that this has been closed. The change log was added on the last release.
