### ISSUE TITLE
html5up.net template not working

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#175]
There is some rendering issue when the web browser control is shown such that the site is not displayed correctly. This is causing people to not be able to use the template.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I just created a new HTML5 UP project using the Alpha template. I then launched the project, with no problems displaying the content. Has this issue been fixed?

**Comment by RandomlyKnighted** [comment]
I have been able to create and run 3 HTML5 UP! templates with no issues. I used the following templates in my test:

Alpha (one of the middle templates created)
Minimaxing (the oldest template on the site)
Spectral (the newest template on the site)

This was tested using version 1.16 of SideWaffle, which is the latest versions at the time of this comment. I'm closing, please reopen if problem persists.

**Comment by panditadata** [comment]
Hello I am using helios from html5up... I changed couple of pictures and now after i refresh the page...the carrousel and all the pictures are gone. Would someone take a look? thanks in advance
https://panditadata.com
