### ISSUE TITLE
Unable to build VS2013

### ISSUE THREAD

**Issue by CallumVass** [ligershark/side-waffle#176]
I am trying to build the solution but I get this error:

Error	2	The "FindVsSDKInstallation" task could not be instantiated from the assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\VSSDK\Microsoft.VsSDK.Build.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.VsSDK.Build.Tasks.FindVsSDKInstallation' to type 'Microsoft.Build.Framework.ITask'.	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\VSSDK\Microsoft.VsSDK.Common.targets	74	5	TemplatePack

I've installed the VS 2013 SDK and have VS 2013 and VS 2010 installed on this machine. Any ideas?

**Comment by RandomlyKnighted** [comment]
@CallumVass are you still experiencing this problem? I ask because I forked the repo back in January and haven't been experiencing any issues with the solution and I'm running Visual Studio 2013 Community Edition.

**Comment by RandomlyKnighted** [comment]
Since this issue was originally started we now check in the binaries so the current build of SideWaffle should build with any version of Visual Studio. If you continue to have problems please reopen with additional details.
