### ISSUE TITLE
AngularJs Typescript Controller Template causes problems with Angular 1.3

### ISSUE THREAD

**Issue by mbeckenbach** [ligershark/side-waffle#182]
The TS controller template using controller as causes some serious trouble when migrating to angular 1.3

I found a solution and posted it into my issue at the angularjs issue list. 
https://github.com/angular/angular.js/issues/9789

Please check if you can update the templates. My way of implementing the controller is much shorter. Not sure if this is the best approach, but at least it works with 1.3. :-)

**Comment by RobHudson72** [comment]
This issue has been driving me absolutely bananas.  @mbeckenbach , thank you very much for the workaround.  I would prefer a solution that uses a class over a function, but it is beyond my expertise.  We really need an AngularJS guru ( @johnpapa ?) to update the template for 1.3

**Comment by RobHudson72** [comment]
I think I found a workaround that allows for the use of classes.  I don't know enough about the controller constructor though to know if this creates additional problems (is the class initialized multiple times?)

It seems to work, but I would appreciate a second set of eyes to see if there are any hidden gotchas before implementing it as a pattern.

```typescript
interface IDemoControllerScope extends ng.IScope {
    vm: DemoController;
}

interface IDemoController {
    greeting: string;
    //controllerId: string;
    changeGreeting: () => void;
}

class DemoController implements IDemoController {
    // this static function is what the controller constuctor calls
    static DemoControllerFnc($scope, $http, $resource) {
        return new DemoController($scope, $http, $resource);
    }
    static controllerId: string = "DemoController";
    greeting = "Hello";
    
    constructor(private $scope: IDemoControllerScope, private $http: ng.IHttpService, private $resource: ng.resource.IResourceService) {
    }

    changeGreeting() {
        this.greeting = "Bye";
    }
}
// Update the app1 variable name to be that of your module variable
app.controller(DemoController.controllerId, ['$scope', '$http', '$resource', ($scope, $http, $resource) =>
    //new DemoController($scope, $http, $resource)
    //controller constructor doesn't create a class, instead it calls a function
    DemoController.DemoControllerFnc
]);

```

**Comment by RobHudson72** [comment]
I have been working on this much of the night and the day, and I haven't been able to improve on the solution provided by @mbeckenbach.  I am officially out of ideas.

Hopefully @johnpapa  or one of the other angular gurus chime in.

**Comment by RobHudson72** [comment]
@mbeckenbach , reviewing your solution, are you certain that vm should implement an interface that extends ng.IScope?  

When I set a breakpoint in the function, after "var vm: IDemo2CtrlScope = this;", vm does not contain any of the ng.IScope members, and vm.$watch returns undefined.  

It doesn't look like vm should implement ng.IScope.  I am guessing that if you want IScope, you have to pass in $scope as a function parameter.

**Comment by kentcooper** [comment]
I'll try to get this fixed and get a PR in tonight but just for your own sanity this should work.
```
interface IDemoControllerScope extends ng.IScope {
    vm: DemoController;
}

interface IDemoController {
    greeting: string;
    //controllerId: string;
    changeGreeting: () => void;
}

class DemoController implements IDemoController {
    static controllerId: string = "DemoController";
    static $inject = ['$scope', '$http', '$resource'];
    greeting = "Hello";

    constructor(private $scope: IDemoControllerScope, private $http: ng.IHttpService, private $resource: ng.resource.IResourceService) {
    }

    changeGreeting() {
        this.greeting = "Bye";
    }
}
// Update the app1 variable name to be that of your module variable
app.controller(DemoController.controllerId, DemoController);
```

**Comment by kentcooper** [comment]
This can probably be closed now. However I was going through the other templates as well and I was wondering is the goal to have them match the non-typescript versions as much as possible? There is considerably less sample code in those versions than in the typescript ones.

**Comment by sayedihashimi** [comment]
@johnpapa own the AngularJS content.

**Comment by kentcooper** [comment]
Well he's definitely a good one to copy from. I'll start making those changes as well than.

**Comment by sayedihashimi** [comment]
Ok sounds good thanks
