### ISSUE TITLE
Dialog to configure remote sources

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#200]
For the [dynamic templates](https://github.com/ligershark/side-waffle/issues/166) we should have a dialog that users can use to configure remote sources.

This dialog should have the following features.

 - [ ] Enable/disable remote sources
 - [ ] Add/Remove new sources
 - [ ] Rebuild all templates

# Walk through
I've created a walk through of what the experience might look like. You can access it in the following links.
 - SideWaffle manage resources: [PPTX format](https://www.dropbox.com/s/2k2fj7o0ek32p6r/SideWaffle%E2%80%93manage-remote-sources.pptx?dl=0) or [PDF format](https://www.dropbox.com/s/zeatr463xv675xu/SideWaffle%E2%80%93manage-remote-sources.pdf?dl=0)

**Comment by RandomlyKnighted** [comment]
I'll be happy to work on this. Creating dialogs in Visual Studio is something I've been wanting to learn for a while now anyways.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted thanks! I've assigned the item to you.

I'm keeping the code in the [```autoupdate```](https://github.com/ligershark/side-waffle/tree/autoupdate) branch. When you have something please send PRs to that branch. Once we have all the features that we need we can merge to ```master```.

If you have any issues getting the code running on your box let me know.

FYI I've created #230 and assigned it to myself. I'll create a class for you to call to read/write the settings.

**Comment by RandomlyKnighted** [comment]
It's a slow process, but I've managed to get this much so far.

![sidewaffle_settings](https://cloud.githubusercontent.com/assets/2483249/5600596/e4110e4a-92a2-11e4-942a-811a3a0ea791.PNG)

I was really hoping to do this with the projects we already had in the solution, but so far I've only been able to get what I have by adding a new VSPackage project to the SideWaffle solution.

**Comment by RandomlyKnighted** [comment]
Just wanted to update this so I know where we are in the dynamic templates feature. Per PR #217 the dialog has been created; however, there is are two bugs that we are aware currently aware of.

1. The menu item shows up multiple times. 
2. The textbox accidentally changes a sources branch when selected.

Other than these two bug I believe this item has been implemented.

**Comment by sayedihashimi** [comment]
I think for the most part things are working now. I'll close this now, from here on we should track these as individual bugs.
