### ISSUE TITLE
Ability to configure the schedule to check for update templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#201]
For the [dynamic templates](https://github.com/ligershark/side-waffle/issues/166) we should have a dialog that users can use to:

 1. Configure the frequency that we check for updated template content
 1. Rebuild all templates (_i.e. clean out all old templates and rebuild from scratch_)

# Walk through
I've created a walk through of what the experience might look like. You can access it in the following links.
 - SideWaffle manage resources: [PPTX format](https://www.dropbox.com/s/2k2fj7o0ek32p6r/SideWaffle%E2%80%93manage-remote-sources.pptx?dl=0) or [PDF format](https://www.dropbox.com/s/zeatr463xv675xu/SideWaffle%E2%80%93manage-remote-sources.pdf?dl=0)

**Comment by sayedihashimi** [comment]
FYI I added a property to store this in a new class ```RemoteTemplateSettings ``` in commit 1ce894d0394dc4873accccef6be06686e272a41c

**Comment by RandomlyKnighted** [comment]
As far as I know, this should be fully implemented now per PR #217.

**Comment by sayedihashimi** [comment]
Closing
