### ISSUE TITLE
Create a method to rebuld all remote templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#204]
We should have a method which callers can invoke which will perform the following operations.

 - [x] Delete the ```Output``` folder under the Extension install directory
 - [x] Delete the folders containing ```sources```, ```baseintout```, and ```output``` under %localappdata%
 - [x] Redownload & build templates from each source listed in ```templatesources.json```

**Comment by RandomlyKnighted** [comment]
I believe the bug you found with deleting the folders is the only thing keeping this item from being fully implemented.
