### ISSUE TITLE
multi-device hybrid apps suport

### ISSUE THREAD

**Issue by julianpaulozzi** [ligershark/side-waffle#207]
Any way to make templates for all "Web" (javascript, html...) available to multi-device hybrid apps (cordova .jsproj) projects?
As the same are based on the same web based tech used in "Web" templates.

**Comment by sayedihashimi** [comment]
Creating templates are the same for every (_as far as I know_) visual studio project, so you should be good to go for cordova/jsproj.

I'll close this issue, but if you run into specific issues please re-open this.

**Comment by julianpaulozzi** [comment]
Yes at some point had only the JavaScript (Tree item) templates in Add New Item.
But after installing Visual Studio Tools for Apache Cordova CTP 3.1 I can see the templates of SideWaffle in "Visual C #> Web> SideWaffle" as well as other.

**Comment by sayedihashimi** [comment]
@julianpaulozzi I think I know what's happening. Cordova hides SideWaffle template item templates. For Cordova you have to author templates specifically for that, which is not an option. See https://github.com/ligershark/side-waffle/issues/227#issuecomment-77780413 for more details. The best course of action 🎬 is to open a new item on http://visualstudio.uservoice.com. If you open an issue please add to #227
