### ISSUE TITLE
Support VSTO - ignore BootstrapperPackage elements

### ISSUE THREAD

**Issue by JohnGoldsmith** [ligershark/side-waffle#212]
Following this StackOverflow thread: http://stackoverflow.com/questions/27924403/how-to-handle-vsto-prerequisites-in-sidewaffle-project-template

VSTO addin project files include ItemGroups as follows (depending on target framework version):

```XML
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.VSTORuntime.4.0">
      <Visible>False</Visible>
      <ProductName>Microsoft Visual Studio 2010 Tools for Office Runtime %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Windows.Installer.4.5">
      <Visible>False</Visible>
      <ProductName>Windows Installer 4.5</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
  </ItemGroup> 
```
These non-file types generate the following errors when building the VSIX project:

*Error	10	Could not copy the file "c:\users\john\documents\visual studio 2013\Projects\ExcelVSTOAddinVSIX\ExcelVSTOAddInTemplate\.NETFramework,Version=v4.5" because it was not found.	ExcelVSTOAddinVSIX*

*Error	11	Could not copy the file "c:\users\john\documents\visual studio 2013\Projects\ExcelVSTOAddinVSIX\ExcelVSTOAddInTemplate\Microsoft.VSTORuntime.4.0" because it was not found.	ExcelVSTOAddinVSIX*

*Error	12	Could not copy the file "c:\users\john\documents\visual studio 2013\Projects\ExcelVSTOAddinVSIX\ExcelVSTOAddInTemplate\Microsoft.Windows.Installer.4.5" because it was not found.	ExcelVSTOAddinVSIX*

As per @sayedihashimi recommendation, manually adding the following to Properties/template-builder.props in the VSIX project solves the problem:
```XML
  <ItemGroup> 
	<ls-NonFileTypes Include="BootstrapperPackage"/> 
  </ItemGroup>
```

**Comment by JohnGoldsmith** [comment]
If ```BootstrapperPackage``` is added to the [default list](https://github.com/ligershark/template-builder/blob/master/tools/ligershark.templates.targets#L75) then the [corresponding item in the wiki](https://github.com/ligershark/side-waffle/wiki/Common-errors-and-gotchas#caveats-for-vsto-project-templates) can be removed.

**Comment by sayedihashimi** [comment]
Added it to the list just now https://github.com/ligershark/template-builder/commit/2118fcdc3128c13544dc8e59c355fcb726d60b44. I will update the wiki after I publish to nuget.
