### ISSUE TITLE
Manifest false error

### ISSUE THREAD

**Issue by NN---** [ligershark/side-waffle#214]
I have manifest.json with the following:

```js
{
    "icons": { "48": "img/icon.png" }
}
```

I got this:

```
Message	1509	The value property "icons" must be of type "Array", but was "{ "48": "img/icon.png" }"	manifest.json	58	14	chromeext
```

According to Chrome documentation it is the correct format: https://developer.chrome.com/apps/manifest
Please fix this false alarm.

**Comment by NN---** [comment]
The only thing is needed is to specify JSON schema by this:

```xml
<UserProperties app_2manifest_1json__JSONSchema="http://json.schemastore.org/chrome-manifest" jscs_1json__JSONSchema="http://json.schemastore.org/jscsrc" />
```

**Comment by sayedihashimi** [comment]
@NN--- can you add a schema directive in the json file itself? 

cc @madskristensen

**Comment by madskristensen** [comment]
To specify the schema in the .json file itself, try to add this to the top of the .json file:
```json
{
  "$schema": "http://json.schemastore.org/chrome-manifest",
  "icons": { "48": "img/icon.png" }
}
```
That will instruct Visual Studio and other JSON Schema aware editors to use that schema

**Comment by NN---** [comment]
@madskristensen It works !
Can you add it to the default manifest.json template ?

**Comment by madskristensen** [comment]
Does it work when the Chrome extension is loaded into Chrome as well? One thing is that it works in VS (we knew it would), another is that Chrome accepts that particular property to be present.

**Comment by NN---** [comment]
Unfortunately not :(
```There were warnings when trying to install this extension:
Unrecognized manifest key '$schema'.```

It seems that the only solution is to change the project file template.

**Comment by RandomlyKnighted** [comment]
@NN---  were you able to figure out a solution to your problem?

**Comment by NN---** [comment]
I found the root cause.
manifest.json uses schema from http://json.schemastore.org/web-manifest
It has following definitions for "icons":

```json
"icons": {
			"description": "The icons member is an array of icon objects that can serve as iconic representations of the web application in various contexts.",
			"type": "array",
			"items": {
				"$ref": "#/definitions/icon"
			}
		},
```

Apparently it should use this one: http://json.schemastore.org/chrome-manifest .

The fix is very simple , use this schema.

```xml
<UserProperties app_4manifest_1json__JSONSchema="http://json.schemastore.org/chrome-manifest" app_2manifest_1json__JSONSchema="http://json.schemastore.org/chrome-manifest" />
```

**Comment by NN---** [comment]
I think it can be added to the template ( https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ProjectTemplates/Web/Chrome%20Extension/ChromeExtensionProjectTemplate.csproj)

**Comment by RandomlyKnighted** [comment]
@NN--- would you be up to creating a PR to fix this issue?
