### ISSUE TITLE
TypeScript files with nested .js and .js.map files.

### ISSUE THREAD

**Issue by NN---** [ligershark/side-waffle#216]
Is it possible to add an item template for TypeScript file which adds nested .js and .js.map flies automatically ?
I use FileNesting extension ( https://visualstudiogallery.msdn.microsoft.com/3ebde8fb-26d8-4374-a0eb-1e4e2665070c ) to make life easier but it is annoying to do it all the time.

**Comment by sayedihashimi** [comment]
See http://stackoverflow.com/questions/12884732/nested-files-in-item-template for some info. If it works and if you have time please consider adding a page/note on the wiki here.

**Comment by NN---** [comment]
If I understand correctly, the ItemTemplate cannot add more than one file.
Am I right ?

**Comment by sayedihashimi** [comment]
Item templates can add many files, for example https://github.com/ligershark/side-waffle/tree/master/TemplatePack/ItemTemplates/Web/ASP.NET/Custom%20T4%20Files.

**Comment by sayedihashimi** [comment]
@NN--- it's pretty easy I just updated a sample template to [nest bootstrap.min.css under bootstrap.css](https://github.com/sayedihashimi/contoso-templatepack/commit/ebfda3675051113166259202e386ef693afdfde5).

Here is what I had before (_which doesn't nest the files_)

```xml
<TemplateContent>
  <ProjectItem ReplaceParameters="true" TargetFileName="Content\bootstrap.css">bootstrap.css</ProjectItem>
  <ProjectItem ReplaceParameters="true" TargetFileName="Content\bootstrap.min.css">bootstrap.min.css</ProjectItem>
  <ProjectItem ReplaceParameters="true" TargetFileName="Content\Site.css">Site.css</ProjectItem>
</TemplateContent>
```

Here is what works

```xml
<TemplateContent>
  <ProjectItem ReplaceParameters="true" TargetFileName="Content\bootstrap.css">bootstrap.css</ProjectItem>
  <ProjectItem ReplaceParameters="true" TargetFileName="Content\bootstrap.css/bootstrap.min.css">bootstrap.min.css</ProjectItem>
  <ProjectItem ReplaceParameters="true" TargetFileName="Content\Site.css">Site.css</ProjectItem>
</TemplateContent>
```

I just added ```bootstrap.css/``` to the file path for the item that I wanted nested under it.
