### ISSUE TITLE
Better support for custom URLs

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#220]
For the dynamic templates the templateSource.json file is currently being stored under the extension directory. The side effect of that is that when the extension is uninstalled/installed all customizations are removed. It would be better to.

 - [x] Store the templateSource.json file in the ```%localappdata%/SIdeWaffle``` folder so that customizations are preserved across versions. We should consider if we want to place it in a version folder or in the root. If in the root if there are breaking changes we should make sure that we "upgrade" the format of the file
 - [x] Have a button on the config page to "Reset Defaults" in the templateSources.json file

**Comment by RandomlyKnighted** [comment]
Per #218 we mentioned that we wanted this to be a part of our second release. However, I was thinking about the button to reset the json file. I believe this could be useful for the first version, that is unless you're expecting second release to come pretty quick after the first.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted if you have time go for it. I noticed that there is a crashing bug in some occasions when using dynamic templates. Once I figure that out and add logging I think we may be good to release. I'll work on it in the next few days and see where we are at.

**Comment by RandomlyKnighted** [comment]
For the "Reset Defaults" button do you think should we download a new copy of the templateSources.json file or just recreate the file programmatically?

**Comment by sayedihashimi** [comment]
Just recreate using the classes. There should be an example in the code already for the case that the file is missing.

**Comment by RandomlyKnighted** [comment]
PR #248 adds the button that resets the json file.

I have not worked yet on moving the ```templatesources.json``` to ```%localappdata%\SideWaffle```. However, based on the original options presented I think having the file in a version folder would be better. It would prevent us from having to remember to "upgrade" the format of the json file.

**Comment by RandomlyKnighted** [comment]
This has been fully implemented.
