### ISSUE TITLE
Add template Reference (sidewaffle project)

### ISSUE THREAD

**Issue by roswilson** [ligershark/side-waffle#223]
I'm using Visual Studio Premium 2012 and installed sidewaffle. I'm following the video https://www.youtube.com/watch?v=z33jOo75CH4&list=UUwEinBp3Mx1UuAR52pzRcNw and cannot see 'Add template Reference (Sidewaffle project )' on the add menu when I right click the project. Do you know how I get this option to show? Thanks.

**Comment by RandomlyKnighted** [comment]
@roswilson are you using the latest version of SideWaffle from sidewaffle.com?

**Comment by sayedihashimi** [comment]
I think the Add Template Reference button is only registered with Visual Studio 2013. I asked @madskristensen to help me fix this. @madskristensen can you fix it?
