### ISSUE TITLE
Prepare for autoupdate release

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#226]
We should rollout the auto update changes incrementally. The first release will include autoupdate but without any template sources configured. We should make the following change

 - [x] Merge latest in ```master``` to ```autoupdate```
 - [x] Change all templates to be embedded (_i.e. not from auto update git feature_)
 - [x] Update the default template settings to not have any configured sources
 - [x] Merge changes from ```autoupdate``` to ```master``` and release

**Comment by RandomlyKnighted** [comment]
@sayedihashimi on the crashes you were encountering earlier the only time I've been able to replicate them was by deleting the folder in ```%localappdata%\LigerShark``` before opening Visual Studio. I then told Visual Studio to rebuild the templates that's when I received the errors. From what I can tell if SideWaffle is in the process of fetching the sources and is told to start fetching them again for whatever reason it will crash. Once the templates finish downloading you can then have it rebuild the templates with no issues. Other than that in that one scenario I have been unable to get it to crash.

**Comment by sayedihashimi** [comment]
![sw-touch-log](https://cloud.githubusercontent.com/assets/1283154/7060208/867300b0-de31-11e4-9827-62a7e97acae2.png)

I think it's trying to set modified time while there is a write handle to it. I will just surround with a try/catch and ignore IOException assuming that when the write is closed the time is updated.

**Comment by RandomlyKnighted** [comment]
Just curious, does File.Create require you to close the file? If so then you might need to close it before setting the last write time.

**Comment by sayedihashimi** [comment]
Yeah I fixed the code in de861ffc791337175356f72094643beec0a9aeaf

**Comment by RandomlyKnighted** [comment]
@sayedihashimi As of my most recent PR I have merged master into autoupdate. Have we already changed all the templates to embedded? If so then we're ready to remove all sources from the ```templatesources.json`` and then merge autoupdate into master.
