### ISSUE TITLE
Asset tags were not added when TemplateBuilder was installed

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#228]
In some cases TemplateBuilder does not add the asset tags when added to the project.

**Comment by sayedihashimi** [comment]
OK I've narrowed it down to reproing in the case where the assets tag looks like the following.

```<Assets />```

Fix coming soon hopefully

**Comment by sayedihashimi** [comment]
I have the fix checked into TemplateBuilder https://github.com/ligershark/template-builder/commit/3bbcf203693708a452cf92c2baf7f6cac5832b6b. Once the build in ```master``` passes I will merge to ```releasetemplatebuilder``` which will then publish to nuget gallery.

The fix will be in templatebuilder nuget package version ```1.1.2-beta6```

**Comment by sayedihashimi** [comment]
Fixed
