### ISSUE TITLE
Override Default Method Stub

### ISSUE THREAD

**Issue by mikecasas** [ligershark/side-waffle#231]
Is there a way to override the default implementation for a method stub? 

It's great that VS creates the method and can even determine the type, but can I modify it so it puts something other than the throw not implemented exception?
![screen2](https://cloud.githubusercontent.com/assets/11261164/6506545/ec3f721c-c319-11e4-8318-1bf0041fb094.png)

**Comment by sayedihashimi** [comment]
That might be implemented with a snippet, but I'm not sure. @madskristensen do you know?

**Comment by madskristensen** [comment]
No idea. I've never seen any code modifying this. I'll be surprised if it's even possible

**Comment by sayedihashimi** [comment]
Evidently you can override it with ```<vs folder>\VC#\Snippets\1033\Refactoring\MethodStub.snippet``` ([source](https://twitter.com/khellang/status/575806185720446976)) but unfortunately that is [no longer supported in VS2015](https://twitter.com/Pilchie/status/575806427442245632).
