### ISSUE TITLE
Sidewaffle release schedule

### ISSUE THREAD

**Issue by RobHudson72** [ligershark/side-waffle#235]
Just checking if there is a plan to update Sidewaffle in the VS gallery soon...

https://visualstudiogallery.msdn.microsoft.com/a16c2d07-b2e1-4a25-87d9-194f04e7a698

Or has attention moved to developing the cloud based version of Sidewaffle that is discussed in another thread?  That sounds great too!

**Comment by sayedihashimi** [comment]
I just published ```1.16```. The gallery still says ```1.0.2``` but when you click on it you'll get the latest. Also update notifications are handled via a custom gallery link so the version in the VS gallery is essentially not important.

That said it is kinda confusing, @madskristensen can you update the gallery to state ```1.16``` for SideWaffle?

**Comment by madskristensen** [comment]
Done

**Comment by sayedihashimi** [comment]
Thanks closing

**Comment by RobHudson72** [comment]
Thank you both!

**Comment by sayedihashimi** [comment]
Btw we now have release notes at http://sidewaffle.com/#releasenotes
