### ISSUE TITLE
Can't set file to open in web browser

### ISSUE THREAD

**Issue by tomhollander** [ligershark/side-waffle#236]
Not sure if I'm doing something silly, but I've spent a couple of hours trying to get a template to show a file in the VS Web Browser upon launch without any success.

I have a file Project_Readme.html in my template project. 
I added the following to my_project.vstemplate.xml file:
```
    <Project TargetFileName="WebApp-OpenIDConnect-DotNet.csproj" File="WebApp-OpenIDConnect-DotNet.csproj" ReplaceParameters="true">
      <ProjectItem OpenInWebBrowser="true" ReplaceParameters="false" TargetFileName="Project_Readme.html">Project_Readme.html</ProjectItem>
    </Project>
```
After compiling, the resulting template package looks OK, but after creating a new project I get an error:
```
The file Project_Readme.html could not be found within the project templates. Continuing to run, but the resulting project may not build properly.
```
And then:
```
Unable to copy the file 'Project_Readme.html' from the project template to the project. Cannot find file "C:\Users\tom\AppData\Local\Temp\szi32k3l.qor\Temp\Project_Readme.html".
```
I've tried changing the `TargetFIleName` to something else (similar result) and omiting `TargetFileName` altogether (NullReferenceException during build). Any suggestions on what I'm doing wrong? Or is there an issue with Sidewaffle?
This scenario is alluded to in https://github.com/ligershark/side-waffle/issues/188 so I'm not sure if it's a known/open problem or I'm doing something wrong?

thanks
Tom

**Comment by sayedihashimi** [comment]
>The file Project_Readme.html could not be found within the project templates. Continuing to run, but the resulting project may not build properly.

You can run into this error if you type the file name wrong or if it's not in the expected location.

One question. Is Project_Readme.html a part of your template project? If not can you add it and then try again?

>Any suggestions on what I'm doing wrong? Or is there an issue with Sidewaffle?

I doubt its an issue with SideWaffle. Have you found any other template (either a vsix or built in) that does what you want? If so then let's take a look at the .vstemplate file.

**Comment by RandomlyKnighted** [comment]
@tomhollander were you able to correct your issue?

**Comment by tomhollander** [comment]
I worked around it by launching it from code in a Wizard extension. I couldn't figure out how to do it declaratively.

**Comment by RandomlyKnighted** [comment]
@tomhollander Alright, then I'm going to go ahead and close this. Feel free to reopen if you have issues with this again. Also if at some point you figure out how to do it declaratively we'd love to hear how you did it.
