### ISSUE TITLE
Multi-project template creates extra folder at root level

### ISSUE THREAD

**Issue by ghost** [ligershark/side-waffle#237]
Following this tutorial: https://github.com/ligershark/side-waffle/wiki/How-to-create-a-multi-project-template

My template solution structure looks like this:

![image](https://cloud.githubusercontent.com/assets/4203100/6755931/bd771d2e-cee3-11e4-8949-cf19bcfa7b7b.png)

When I create a project using the VSIX, there is an additional folder created at the root level. 

![image](https://cloud.githubusercontent.com/assets/4203100/6755980/10ab7f8a-cee4-11e4-97fd-14a16519ae12.png)

Is there any way to not have this folder generated?

**Comment by sayedihashimi** [comment]
Good question, I'm not sure. I haven't looked at multi-project templates in a while so I forgot how the work. Multi-project templates are tricky. I would think that you should be able to do this, but not exactly sure.

FYI the .vsix file is a zip file so you can rename to .zip and extract it to see the contents. Inspecting that and playing around with it may help you identify the issue. Sorry I don't have more info for you.

**Comment by maheshw** [comment]
Looks like this is the same issue I was having: http://stackoverflow.com/questions/3882764/issue-with-visual-studio-template-directory-creation

I will report back after trying the given solution. Thanks

**Comment by sayedihashimi** [comment]
Thanks, if we need to modify (or add a new) the wizard in TemplateBuilder we can.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi is this similar to the issue found reported by @gaspode44 on #169?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted yeah it sounds like the same issue. Looks like the solution is to use a custom wizard, see http://stackoverflow.com/questions/3882764/issue-with-visual-studio-template-directory-creation.

**Comment by sayedihashimi** [comment]
For the folder issue maybe the ['SolutionWizard'](https://github.com/ligershark/template-builder/blob/6184bec12552ed32bfc573a05a01bb9f57514b97/src/TemplateBuilder/SolutionWizard.cs) will help you. More info on that at https://github.com/ligershark/template-builder/pull/79.

**Comment by RandomlyKnighted** [comment]
This should now be fixed via the new pecan-waffle solution that @sayedihashimi has developed. You can find the video for it here: http://youtu.be/ysvTROB963k
