### ISSUE TITLE
 AngularJS provider template

### ISSUE THREAD

**Issue by kentcooper** [ligershark/side-waffle#242]
Received a request on the VS Extensions site https://visualstudiogallery.msdn.microsoft.com/a16c2d07-b2e1-4a25-87d9-194f04e7a698 QA section, to create an AngularJS provider template. @johnpapa  wanted to check to see if you wanted to handle this or if you had any feedback. If not I can create it and the matching TS version as well.

**Comment by johnpapa** [comment]
Go for it!

**Comment by kentcooper** [comment]
Template added
