### ISSUE TITLE
AngularJS Project Template

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#244]
We should add a project template to get started with asp.net and AngularJs.

**Comment by kentcooper** [comment]
So I'm trying to decide which way to go with this. Are we looking at a basic template with just the minimum needed to run an angular app? Or are we looking to get a angular/web api app up and going?

**Comment by johnpapa** [comment]
I say basic angular with simple aspnet web API and single index HTML. No MVc

Sent from Outlook




On Tue, Apr 7, 2015 at 5:33 PM -0700, "Kent Cooper" <notifications@github.com> wrote:












So I'm trying to decide which way to go with this. Are we looking at a basic template with just the minimum needed to run an angular app? Or are we looking to get a angular/web api app up and going?

**Comment by kentcooper** [comment]
Okay well the original request was for an "empty NG" template and I have that now. Right now I'm using Global.asax to register the API config. I normally use Owin myself but I'm not sure if that's the route we want to go with this or if we want to keep the number of dependencies to a minimum.

**Comment by johnpapa** [comment]
ah, was it? ok.

I hate messy starter templates. Ideally the MVP is a no back end angular app. but people are in VS cuz they want some back end, likely asp.net. so my thinking is thats a good MVP. simple server would be great. just serve a page, have a single api, and go away

**Comment by kentcooper** [comment]
Okay so I checked in the basic starter template [here](https://github.com/kentcooper/side-waffle/tree/angular-project-template/TemplatePack/ProjectTemplates/Web/AngularJSWebApiEmpty). I'm not even adding an API controller just the dependencies and basic folder structure. I did add the app.js file just to kind of start it out. I'm still thinking about making it use OWIN. Anyway if you get a chance to look at it I'd appreciate the feedback.

**Comment by sayedihashimi** [comment]
@kentcooper can you build the .vsix file and share that so that it's easy for people to test it?

**Comment by kentcooper** [comment]
Okay here it is. http://1drv.ms/1aPrUst

**Comment by RandomlyKnighted** [comment]
@kentcooper I just tested out your template but ran into an issue with the Global.asax.cs and WebApiConfig.cs. They were calling a couple of depdencies but couldn't recognize that they were there. I had to reinstall the package Microsoft.AspNet.WebApi.WebHost in order to fix the errors.

```
Update-Package -reinstall Microsoft.AspNet.WebApi.WebHost
```

is what I used to correct the issue.

**Comment by kentcooper** [comment]
hmmm... I would have thought that nugget package restore would have restored the dependencies automatically on build.

**Comment by RandomlyKnighted** [comment]
@kentcooper That was the only package I had issues with. Everything else was added automatically on build.

**Comment by kentcooper** [comment]
@sayedihashimi have you run into that before? Is there anything I need to do to allow it to be restored properly?

**Comment by sayedihashimi** [comment]
Sorry for the delay here, I lost this and didn't realize it was waiting on me.

I looked at the generated project and all the HintPath values are messed up. For example.

```
<Reference Include="Newtonsoft.Json">
    <HintPath>..\..\..\..\..\..\..\users\kent\documents\visual studio 2013\Projects\AngularJSWebApiEmpty\packages\Newtonsoft.Json.6.0.4\lib\net45\Newtonsoft.Json.dll</HintPath>
</Reference>
```

Where they should look more like the following.

```
<Reference Include="Newtonsoft.Json">
    <HintPath>..\packages\Newtonsoft.Json.6.0.4\lib\net45\Newtonsoft.Json.dll</HintPath>
</Reference>
```

Once I changed all the hint paths to the above the project worked.

**Comment by kentcooper** [comment]
ahh... alright. I'll get those fixed.
