### ISSUE TITLE
Automate the publish process

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#247]
We should automate the publish process so that we can easily publish and so that I am not the bottleneck to get a release out the door.

We should create a new branch ```release``` and whenever this branch is checked in the following files should be published.
 - [x] TemplatePack.vsix -> sidewaffle.com/feed/web/TemplatePack.vsix 
 - [x] source.extension.vsixmanifest -> sidewaffle.com/feed/web/extension.vsixmanifest
 - [x] release-notes.html -> sidewaffle.com/release-notes.html

**Comment by RandomlyKnighted** [comment]
@sayedihashimi would it be possible for me to learn how this is done as well so I can carry it over to my other projects?

**Comment by sayedihashimi** [comment]
Yeah once I complete it I can review the changes with you and explain them.

**Comment by sayedihashimi** [comment]
Related commits
 - e3f4390375fe0b02ff77755a5df468f63465e52f
 - 68e6206b38607e943fb1b6eb5226bcfb845c7d7e
 - e9d49f6149431f5406f07ad529fa653aed613670

**Comment by sayedihashimi** [comment]
OK this is done now. I will write up info on the publish process to the wiki hopefully tomorrow.
