### ISSUE TITLE
autoupdate: Schedule should be a radio button group not checkboxes

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#250]
For autoupdate settings we are using checkboxes, where they should be radio buttons so that only 1 can be selected.

We should also add a "Always" option which will check for an update every time VS is started.

@RandomlyKnighted can I assign this to you?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi sure, but could you elaborate on the always option? Shouldn't it do that check anyways?

**Comment by sayedihashimi** [comment]
If I pick "Check once a Month" it should check once a month for new templates. If I check "Always" it should check for updated templates everytime I start VS. does that make sense?

**Comment by RandomlyKnighted** [comment]
Yep though I was thought that was already implemented it, but I'll check it out.

**Comment by sayedihashimi** [comment]
I think it checks for ***new sources*** every time and for existing ones it will fetch from git based on the schedule. The always option is really for us.

**Comment by RandomlyKnighted** [comment]
OK so I guess the question now is how do you tell if a template has been updated? Should we look for anything specific from the source destination or should we keep track some other way?

**Comment by RandomlyKnighted** [comment]
I just wanted to note on here that there is currently a bug where if you change the update frequency the dialog either is not saving the new frequency or it is loading the incorrect one. I'll have to do some debugging to figure out which one it is. 

Here's my current to do list:
- [X] Change update frequency checkboxes to radio buttons
- [X] Add an option for "Always" in update frequency settings
- [ ] Fix issue where settings does not check to see if a template has been updated
- [ ] Fix issue where the settings window either does not save the frequency correctly or shows the wrong setting

**Comment by RandomlyKnighted** [comment]
@sayedihashimi  I've got everything working now except for where it checks to see if a template has been updated. Because our sources can be either a git repository or a location on the file system, how do we determine if the source has been updated?

**Comment by RandomlyKnighted** [comment]
The original request made here has been completed via #252.
