### ISSUE TITLE
Doc creation: add wiki articles for item templates and snippets

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#254]
With the upcoming release of the MSDN article, it would probably be a good idea to create wiki articles showing how to create an item template and for adding new snippets. Currently, the item templates wiki page just points to a blog post and there is no wiki page for snippets.

**Comment by sayedihashimi** [comment]
There is some info on snippets at https://github.com/ligershark/side-waffle/wiki/How-to-create-your-own-template-pack

**Comment by RandomlyKnighted** [comment]
Do we want to just use that as our go-to Snippets wiki article or should I add a more detailed version with screenshots?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted I think we can go with what we have for now on snippets. I think there are other things more important.
