### ISSUE TITLE
No Chrome project work

### ISSUE THREAD

**Issue by port513** [ligershark/side-waffle#257]
Trying to use the Chrome templates.
In all teplates I get this error

"CompressFiles or CompressPath must be specified ChromeExtensionProjectTemplate4"

I just create the project and try to build it but it always fail.

I'm using Visual Studio 2013 Professional with a Swedish version of Windows 7 x64

**Comment by sayedihashimi** [comment]
OK I made some changes in 6861000ed2302d40921235841a8d1bdfee5956d0. Check out the comments there for more details. 

I have a build ready for testing at https://dl.dropboxusercontent.com/u/40134810/SideWaffle/issue-257/TemplatePack.zip.

I've already committed to master so the fix should be in the next release.

**Comment by port513** [comment]
Maybe I do something wrong but when I reload the solution and CTRL + F5 I don't see the extension in Chrome.
Do I have to enable anything in Chrome to allow this?

**Comment by RandomlyKnighted** [comment]
@port513 here's what I did to get the extension to test in Chrome:

1. Turn on Chrome's extension developer mode located on the Chrome extensions page
2. Click the button labeled Load unpacked extension...
3. Navigate to your project's bin folder and selected the folder labeled "unpacked" then hit the OK button.

Once you do that you should see your extension appear to the right of the address bar. It's now ready for you to start testing.

**Comment by sayedihashimi** [comment]
It used to be automated on CTRL+F5 after the solution was closed/reopened one time. I think something changed on the chrome end. @port513 if you figure out how to automate from the command line then we should be able to replicate that.

I'll close this now but if you figure out steps to automate that please re-open.
