### ISSUE TITLE
Create an xunit project template for ASP.NET 5

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#259]
We should add a new project template for xUnit ASP.NET 5.

I am working on getting the content of the template ready and will update this when I have that.

**Comment by sayedihashimi** [comment]
OK I have the xUnit test project at https://dl.dropboxusercontent.com/u/40134810/SideWaffle/issue-259/UnitTestProject.zip which is ready to go.

**Comment by kentcooper** [comment]
Not sure if you were looking for feedback on this but downloaded it and ran the default test with now problems. Also created a few other ones and those all ran fine as well.

**Comment by RandomlyKnighted** [comment]
This was added in [release v1.19](https://github.com/ligershark/side-waffle/releases/tag/v1.19).
