### ISSUE TITLE
Create a Gulp configuration item template

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#261]
Since VS 2015 is going to be using Gulp as one of its main task runners, I think it would be great if we added an item template that creates a basic gulpfile.js file. We've already got an item template for GruntJS so I think this would an excellent addition to our item templates.

**Comment by RandomlyKnighted** [comment]
For this item template I was thinking about keeping it simple and just adding a gulpfile.js and including the following:

```javascript
var gulp = require('gulp');

gulp.task('default', function() {
  // place code for your default task here
});
```

@kentcooper is there anything else that you think would need to be added?

**Comment by sayedihashimi** [comment]
What I would recommend here is to create two item templates

 - Gulp file (basic)
 - Gulp file

Here ```Gulp file (basic)``` is the sample content from the [gulp getting started guide](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md) which is exactly what you have above, so +1.

```Gulp file``` is the content that you get from an ASP.NET 5 project created in VS2015 RC which I've pasted below.

```javascript
/// <binding Clean='clean' />

var gulp = require("gulp"),
  rimraf = require("rimraf"),
  fs = require("fs");

eval("var project = " + fs.readFileSync("./project.json"));

var paths = {
  bower: "./bower_components/",
  lib: "./" + project.webroot + "/lib/"
};

gulp.task("clean", function (cb) {
  rimraf(paths.lib, cb);
});

gulp.task("copy", ["clean"], function () {
  var bower = {
    "bootstrap": "bootstrap/dist/**/*.{js,map,css,ttf,svg,woff,eot}",
    "bootstrap-touch-carousel": "bootstrap-touch-carousel/dist/**/*.{js,css}",
    "hammer.js": "hammer.js/hammer*.{js,map}",
    "jquery": "jquery/jquery*.{js,map}",
    "jquery-validation": "jquery-validation/jquery.validate.js",
    "jquery-validation-unobtrusive": "jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"
  }

  for (var destinationDir in bower) {
    gulp.src(paths.bower + bower[destinationDir])
      .pipe(gulp.dest(paths.lib + destinationDir));
  }
});
```
