### ISSUE TITLE
AngularJS filter template

### ISSUE THREAD

**Issue by olsh** [ligershark/side-waffle#264]
Add AngularJS filter template like in the sublime version
https://github.com/johnpapa/angular-styleguide/blob/master/assets/sublime-angular-snippets/angular.filter.sublime-snippet

**Comment by RandomlyKnighted** [comment]
@kentcooper would you like to work on this?

**Comment by kentcooper** [comment]
Yeah I'll make one.

**Comment by johnpapa** [comment]
lol. i hate filters :)

yes, i created one, but i hate em

**Comment by kentcooper** [comment]
So you're saying you don't want to make this one? :-)  Really I'm not a fan either. I can see where they'd be useful but I avoid them like a plague.

**Comment by kentcooper** [comment]
@johnpapa I know you don't like filters but I had to add you to the credits on the template. Now you will be forever associated with filters! *evil laugh*

**Comment by johnpapa** [comment]
oh, thanks :)
