### ISSUE TITLE
Create a Bower item template

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#268]
In VS 2015, there is a Bower item template. It would be nice if we could add the same item template for those who are using older versions of Visual Studio. The item template from VS 2015 looks like this:

```json
{
	"name": "WebApplication2",
	"private": true,
	"dependencies": {
	}
}
```

**Comment by RandomlyKnighted** [comment]
Where should this item template go? We only have 2-3 json files in SideWaffle and they all have different categories. For example, we have the json file for tslint which is under the Web/JavaScript category and we have the Json Schema item template which is under the Web/Misc category.

**Comment by sayedihashimi** [comment]
+1, it should go under Web

**Comment by RandomlyKnighted** [comment]
Alright, what about the subfolder under Web? Since it's JSON would it be classified as JavaScript or Misc?

**Comment by sayedihashimi** [comment]
It doesn't have to go into any subfolder. Directly in web is ok.

**Comment by RandomlyKnighted** [comment]
Good to know. Thanks @sayedihashimi

**Comment by RandomlyKnighted** [comment]
@sayedihashimi what do I do about a templateId since we haven't released a new version of SideWaffle since you added the fix?

**Comment by sayedihashimi** [comment]
Create a new guid and add TemplateID element
