### ISSUE TITLE
Javascript project templates

### ISSUE THREAD

**Issue by pputhran** [ligershark/side-waffle#270]
How can i create a project template for Javascript (example a custom NodeJS project template)

**Comment by RandomlyKnighted** [comment]
@pputhran, thanks for using SideWaffle. Please refer to our wiki article regarding [How to create a project templates](https://github.com/ligershark/side-waffle/wiki/How-to-create-a-project-template). If you have any questions, feel free to post back here.

**Comment by pputhran** [comment]
thanks for a quick response @RandomlyKnighted . I tried following the article and built the vsix (exactly like the one in the article/video) but I dont see my custom project in Visual studio template. I am using Visual Studio 2013 community version. Would that make any difference.

**Comment by RandomlyKnighted** [comment]
No, did you double click the VSIX to install your template? If so, then restart Visual Studio and the template should show up.

**Comment by pputhran** [comment]
Still didnt work

_project.vstemplate.xml

<VSTemplate Version="3.0.0" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" Type="Project">
  <TemplateData>
    <Name>Pawan</Name>
    <Description>Project description here</Description>
    <DefaultName>WpfApplication1</DefaultName>
    
    <ProjectType>CSharp</ProjectType>
    <ProjectSubType></ProjectSubType>
    <SortOrder>1000</SortOrder>
    <CreateNewFolder>true</CreateNewFolder>    
    <ProvideDefaultName>true</ProvideDefaultName>
    <LocationField>Enabled</LocationField>
    <EnableLocationBrowseButton>true</EnableLocationBrowseButton>
    <Icon>sw-file-icon.png</Icon>
    
    
    <NumberOfParentCategoriesToRollUp>1</NumberOfParentCategoriesToRollUp>
    
  </TemplateData>
  <TemplateContent>
    <Project TargetFileName="WpfApplication1.csproj" File="WpfApplication1.csproj" ReplaceParameters="true">      
    </Project>
  </TemplateContent>
</VSTemplate>

=========================
_preprocess.xml:

<?xml version="1.0" encoding="utf-8" ?>
<Preprocess>
  
  <TemplateInfo Path="CSharp\Windows\SideWaffle"/>
  <Replacements Include="*.*" Exclude="*.vstemplate;*.fsproj;*.vbproj;*.jpg;*.png;*.ico;_preprocess.xml;_project.vstemplate.xml">
    <add key="WpfApplication1" value="$safeprojectname$"/>
  </Replacements>
</Preprocess>

**Comment by RandomlyKnighted** [comment]
When you added the SideWaffle Project Template files, was TemplateBuilder added as a reference to your project?

**Comment by pputhran** [comment]
correct. vsix project in my solution has the reference to templatebuilder

**Comment by RandomlyKnighted** [comment]
@sayedihashimi am I forgetting anything?

**Comment by sayedihashimi** [comment]
Is the project file on disk named ```WpfApplication.csproj```? If the name in the ```_project.vstemplate.xml``` doesn't match what's on disk then this could happen. If that is not it could you follow the video step by step for a generic project type and let us know if that works or not?

**Comment by pputhran** [comment]
Thank you @sayedihashimi 

I followed the step by step video tutorials and that appears to work. I am actually trying to create a project template for Node.JS application. What should my <TemplateInfo Path=""/> and <ProjectType></ProjectType> be?

And is it the same steps (as in the video above) for creating a NodeJS (javascript) project template?

**Comment by pputhran** [comment]
I think I got it working for Javascript projects as well. One minor problem that I still have, when I create a new project (via Experimental Instance), the project file contains _Definitions folder. How do I get rid of this? 
![definitions](https://cloud.githubusercontent.com/assets/6620128/7919273/1872f3ee-088f-11e5-8b1f-e140820f63a0.PNG)

**Comment by sayedihashimi** [comment]
In the source project just exclude that folder from the project. Can u create a new issue for that so we can fix the underlying issue?

**Comment by RandomlyKnighted** [comment]
Since you were able to find a workaround and have opened a separate issue for the underlying issue, I'm going to close this. If you have any more problems, feel free to reopen.
