### ISSUE TITLE
Add SortOrder to all item templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#272]
All item templates should have a ```SortOrder``` filed which is set to a minimum value of ```1000```.

**Comment by kentcooper** [comment]
Is it alright if they are all set to 1000? I can write a script that will add it if so.

**Comment by RandomlyKnighted** [comment]
From what I've read in the [MSDN documentation](https://msdn.microsoft.com/en-us/library/ms171389.aspx) (shown below) it should be fine if they are all set to 1000, because the default value is 100. So all our templates should appear after the default templates.

```text
SortOrder is an optional element. The default value is 100, and all values must be multiples of 10.

The SortOrder element is ignored for user-created templates. All user-created templates are sorted alphabetically.

Templates that have low sort order values appear in either the New Project or New Add Item dialog box before templates that have high sort order values.
```

**Comment by sayedihashimi** [comment]
Ok

**Comment by kentcooper** [comment]
Modified @sayedihashimi's scripts to add these. Script can be found [here](https://gist.github.com/kentcooper/cdd8db12d504d992683c).

**Comment by RandomlyKnighted** [comment]
I think we should update the SideWaffle Item Template so that any new item templates have this as well.

**Comment by kentcooper** [comment]
Good idea! Added it to my PR

**Comment by sayedihashimi** [comment]
Thanks guys!
