### ISSUE TITLE
Support for Aurelia?

### ISSUE THREAD

**Issue by mcquiggd** [ligershark/side-waffle#273]
The team have provided good support for Durandal, and Mads has implemented support for Aurelia in Web Essentials.... 

Are there plans to add template and snippet support for Aurelia? It would seem to be a great match for the SideWaffle project, to support a standards-based (ES6, ES7, Web Components), non-opinionated framework, that is modular, plays nicely with existing libraries such as Breeze.js, Knockout etc, and aims to provide an upgrade path from Durandal, Angular ... 

http://aurelia.io/

**Comment by RandomlyKnighted** [comment]
To my knowledge, I'm not sure if we have anyone at the moment (besides Mads) who has experience with Aurelia. If someone who has experience with it would like to contribute some templates and/or snippets, we'd appreciate the contribution.

**Comment by sayedihashimi** [comment]
@EisenbergEffect what your plan for Project / Item templates for Visual Studio for Aurelia? If you don't have any plans then we can add templates to SideWaffle.
If you're planning to create your own template pack, then I'd love for you to try and use TemplateBuilder to simplify creating that template pack.

**Comment by EisenbergEffect** [comment]
@sayedihashimi I haven't tried to create templates for a long time. It used to be quite cumbersome. I would like to have those for VS if possible though. Can you point me in the direction of the latest docs on how to achieve this most easily? I will try to put one of our team members on it. We've got a few that use VS as their primary tool, so it's good motivation for them.

**Comment by sayedihashimi** [comment]
@EisenbergEffect see the wiki, the best doc to get started with is https://github.com/ligershark/side-waffle/wiki/How-to-create-a-project-template.

If you need any help let me know.

**Comment by EisenbergEffect** [comment]
@cmichaelgraham Can you look into this? I think it's a good fit for your skills and experience.

**Comment by mcquiggd** [comment]
Impressed to see such a rapid responsive. 

@EisenbergEffect 

If I can be of assistance, I would like to volunteer a portion of my time, if you require additional 'hands' or 'eyes' to assist with the development, testing / QA.

**Comment by EisenbergEffect** [comment]
@mcquiggd Would love to have some help on this. @cmichaelgraham has been doing most of our VS experiments. I think he's off the grid right now. If you want to take it on, feel free. Send me email (you can get it from my github profile) and I will connect you with Michael so you two can coordinate.

**Comment by mcquiggd** [comment]
Will do so, thanks Rob.

**Comment by mcquiggd** [comment]
@EisenbergEffect

Rob - contact details sent to your 'bluespire' account.

David

**Comment by sayedihashimi** [comment]
Thanks guys. If you have any problems creating the templates let me know and I can help out.

**Comment by RandomlyKnighted** [comment]
@mcquiggd @EisenbergEffect I'm about to be at an in between stage for implementing SideWaffle features if you need any help with this.

**Comment by EisenbergEffect** [comment]
@mcquiggd We would love for you to work on this if you are still interested.

**Comment by RandomlyKnighted** [comment]
@EisenbergEffect I noticed in the Aurelia Docs that there is a getting started package. Is that package what you had in mind for adding to SideWaffle or was you wanting something more involved?

**Comment by EisenbergEffect** [comment]
We would want to use our official production quality starter kits rather than our beginner kits.

**Comment by RandomlyKnighted** [comment]
Do you have a link to these production starter kits? If so, I'll be happy to see if I can add these to SideWaffle.

**Comment by EisenbergEffect** [comment]
All the info you need should be here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.1/doc/article/a-production-setup

**Comment by RandomlyKnighted** [comment]
Do we want a project template for each of the skeletons or do we want to do one template for ES2016 and one one TypeScript? I'm happy to do it; however, you like. I should be able to get these templates made either tonight or tomorrow.

**Comment by EisenbergEffect** [comment]
There are two asp.net projects in the download, one for es2016 and one for TS. I think those would be good candidates.

**Comment by RandomlyKnighted** [comment]
Yep, I see them. Thanks! I'll start on them tonight.

**Comment by RandomlyKnighted** [comment]
@EisenbergEffect I've created the templates and have since reached out to Mike Graham and Patrick Walters about testing them before we release the templates to the public. Mike said that he won't be able to test this for a while and I'm waiting to here back from Patrick. Is there anyone else on your team that you would recommend that I reach out to?

**Comment by EisenbergEffect** [comment]
Those are the best to people for Windows stuff I think. Maybe Matt Davis?

**Comment by RandomlyKnighted** [comment]
Alright I'll reach out to him as well. Thanks for the quick update.

**Comment by RandomlyKnighted** [comment]
@EisenbergEffect I hope to have a PR ready tonight that will include the Aurelia templates. From looking at the skeleton-navigation repo it looks like there have been several updates since I started working on this. When I downloaded the skeleton projects you were on version `1.0.0-beta.1.1.2` and now it looks like you're on `1.0.0-beta.1.1.6` now. Seeing as releasing a new version of these templates roughly once a week how often do we want to update these templates?

**Comment by EisenbergEffect** [comment]
It's hard to answer the question of frequency. If you are willing to maintain the VS integration, what type of frequency would you be comfortable with? How hard is it to make updates?

**Comment by RandomlyKnighted** [comment]
I'm up to maintaining it for now. I'm hoping manual updates will be soon be unnecessary with what @sayedihashimi and I have planned for SideWaffle.

As far as how hard it is to make updates that really depends on how much is changed with each version. If only a file or two is changed then I can just replace the old file with the new one and submit that. If a new version has several files updated it might be easier to replace the whole project with the newer version, which now that I'm getting the hang of creating ASP.NET 5 templates with SideWaffle shouldn't be as bad as it was this first time.

**Comment by RandomlyKnighted** [comment]
@EisenbergEffect I should probably add that the hardest part of updating the templates is keeping up with what's changed from version to version. If someone on the Aurelia team can just update me every so often with what's changed I'll be happy to update the templates however often you like even if I need to dedicate a night each week to update and test the templates I'm happy to do it.

**Comment by EisenbergEffect** [comment]
We can certainly notify you. If that's all it takes, we can put something in place to make sure you get the info you need.

**Comment by RandomlyKnighted** [comment]
@EisenbergEffect Sounds good.

**Comment by lucamorelli** [comment]
I have small sample applications using aurelia, asp.net 5 rc 1 and ts that are working fine and I think is not a big problem to create a sample project. I would like to add the management of authentication but I'm having an hard time on how to handle it in a simple way using rc 1.
Beside this, I think I need to clean up the code because could be there is inside older code from previous versions of the aurelia packages.

**Comment by RandomlyKnighted** [comment]
@lucamorelli what did you do to get around the issues mention in https://github.com/aurelia/skeleton-navigation/issues/325? If I can work past those issues I believe I can get the templates updated and finished fairly quickly.

**Comment by lucamorelli** [comment]
Honestly I don't use it at all, I started from scratch, anyway if you're using typings try to exclude "typings/main.d.ts" in the ts.config

**Comment by RandomlyKnighted** [comment]
@EisenbergEffect I saw that my second PR (https://github.com/aurelia/skeleton-navigation/pull/367) was merged today.  Seeing as there are so many moving parts in these templates I'd prefer to pull from a release. Will there be another one soon that I can pull from?

**Comment by EisenbergEffect** [comment]
Yes. Tomorrow is the plan.

**Comment by RandomlyKnighted** [comment]
That's great! Thanks!

**Comment by RandomlyKnighted** [comment]
Alright, I've added a PR that includes both an ES2016 and a TypeScript template for ASP.NET Core. 

Once merged, I'll maintain these templates. @EisenbergEffect you said that it was possible to put something in place so that I know when these two skeleton templates have changed in a release. Can we still do that?

**Comment by EisenbergEffect** [comment]
@RandomlyKnighted I think that if you "watch" the skeleton-navigation repo on Github you should get notified whenever there's activity on that repo. Would that work well enough for you?

**Comment by RandomlyKnighted** [comment]
Yes, that'll work. Thanks!
