### ISSUE TITLE
Image file corrupted in the template

### ISSUE THREAD

**Issue by jckh1234** [ligershark/side-waffle#274]
I have build a vsix project in vs2013 for my custom web application template. I have several images file (png) in my web template. 

The vsix build and install without error, however I found all the image files are corrupted in my project that I created by the template.

The images file size is the same as the original file but cannot open in browser or image viewer.

If I use Export Template wizard in vs2013, it works fine.

**Comment by sayedihashimi** [comment]
Can you share the sample?

**Comment by kentcooper** [comment]
Closing for now. @jckh1234 if you can give us an example or more detail we can reopen.
