### ISSUE TITLE
Missing Item Templates for VS projects

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#276]
There are a few item templates that show up in the ```Add New Item``` dialog for C# projects that do not show up for VB projects. These templates should be in both types of projects since they are used when creating your own template pack.

All items should show up under the ```Extensibility->SideWaffle``` node.
* Package Definition (.pkgdef)
* SideWaffle Definitions Folder
* SideWaffle Item Template

**Comment by RandomlyKnighted** [comment]
@sayedihashimi In the ["SideWaffle Item Template" item template](https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/CSharp.vstemplate#L12), we are using ```$guid1$``` instead of actually adding a TemplateId like in other item templates?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted yes that looks like an error.

**Comment by RandomlyKnighted** [comment]
This was fixed in PR #278
