### ISSUE TITLE
Updating invalid TemplateIds

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#277]
There are ~10 files that contain invalid TemplateIds, i.e. ```$guid1$```. I briefly looked over the PowerShell script that added the TemplateIds and noticed that any Ids that were already existing were ignored. 

I think we should probably update the current script to so that instead of skipping a file that already contains a TemplateId it should verify that its value is valid.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted for those files I think we can manually add a guid. Updating the script may not be worth it since they are a special case.
