### ISSUE TITLE
Missing OpenInWebBrowser, Broken HintPath and Better Debugging

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/side-waffle#283]
Moved from [here](https://github.com/ligershark/side-waffle/issues/172), so I don't hijack the thread.

Thank you for your offer of help, I really appreciate it. I have now created a project template using [these](https://github.com/ligershark/side-waffle/wiki/How-to-create-a-project-template) SideWaffle instructions and can report some issues:

1 - I used the following XML in my old template project to open a [ReadMe](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC5/Boilerplate.Web.Mvc5.Sample/ReadMe.html) file on project generation. Is there a way to do this using SideWaffle? My ReadMe is core to the project and provides a check-list that remembers what the user has selected using persist-js, so I don't want to lose this feature.
```
<ProjectItem ReplaceParameters="true" OpenInWebBrowser="true">ReadMe.html</ProjectItem>
```
2 - The HintPath is not being corrected. The old VSIX outputs to ```..\packages``` by default, while SideWaffle is outputting what was in my project ```..\..\packages``` which is causing a build error.

3 - This is minor. Is there some way we can run the project we want to turn into a template for debugging/testing. Having to create a new project from the template and copy things back to the template will slow down my work-flow.

I have been thinking about using a custom wizard. How does the One ASP.NET dialogue handle adding the [ASP.NET Identity](http://www.asp.net/identity/overview/getting-started/introduction-to-aspnet-identity) authentication? This requires NuGet packages and cs/cshtml files to be added/updated and is not trivial. I assumed it somehow magically did this for you. Writing this myself sounds like it might be complicated.

**Comment by RandomlyKnighted** [comment]
You can hit Ctrl + F5 to load the template in an experimental instance of Visual Studio. This will allow you to test your template without actually installing it.

**Comment by RehanSaeed** [comment]
Thanks @RandomlyKnighted, good to know.

**Comment by RandomlyKnighted** [comment]
As for Question 2, we could add a check to see if there is an incorrect value in the HintPath. 

@sayedihashimi what do you think about adding this in with the code for the Template Reference? Since the project will probably have to be reloaded after fixing the HintPath, I figure that would probably be the best place for it. That way we only have to reload the project once.

**Comment by sayedihashimi** [comment]
For 1: you should be able to add that in the vstemplate.xml file. If you've tried that and it didn't work let me know and I'll look into it.

For 2: if the value of HintPath needs to change from ```..\..\packages``` to ```..\packages``` then you can add a replacement in ```_preprocess.xml```. Make sure to remove the ```*.csproj``` value from the exclude list in ```_preprocess.xml```. More info on replacements at https://github.com/ligershark/side-waffle/wiki/How-replacements-work

@RandomlyKnighted 
>@sayedihashimi what do you think about adding this in with the code for the Template Reference? 

It may not be worth the effort, instead we can implement #172.

**Comment by RehanSaeed** [comment]
1 - I added the following code and got an error:

```
<VSTemplate Version="3.0.0" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" Type="Project">
  <TemplateData>
    <Name>ASP.NET MVC 5 Boilerplate</Name>
    <Description>A professional ASP.NET MVC template for building secure, fast, robust and adaptable web applications or sites. It provides the minimum amount of code required on top of the default MVC template provided by Microsoft. Find out more at RehanSaeed.com</Description>
    <Icon>sw-file-icon.png</Icon>
    <ProjectType>CSharp</ProjectType>
    <ProjectSubType></ProjectSubType>
    <RequiredFrameworkVersion>4.5</RequiredFrameworkVersion>
    <SortOrder>1000</SortOrder>
    <TemplateID>f2d50b53-cff3-41b4-8481-dac14c18ea48</TemplateID>
    <CreateNewFolder>true</CreateNewFolder>
    <DefaultName>WebProject</DefaultName>
    <ProvideDefaultName>true</ProvideDefaultName>
    <LocationField>Enabled</LocationField>
    <EnableLocationBrowseButton>true</EnableLocationBrowseButton>
    <!-- Indicates how many parent folders this item template should appear in -->
    <NumberOfParentCategoriesToRollUp>1</NumberOfParentCategoriesToRollUp>
  </TemplateData>
  <TemplateContent>
    <Project TargetFileName="$projectname$.csproj" File="Boilerplate.Web.Mvc5.Sample.csproj" ReplaceParameters="true">
      <ProjectItem ReplaceParameters="true" OpenInWebBrowser="true">ReadMe.html</ProjectItem>
    </Project>
  </TemplateContent>
</VSTemplate>
```

```
1>C:\Git\ASP.NET-MVC-Boilerplate\Source\packages\TemplateBuilder.1.1.3\tools\ligershark.templates.targets(512,5): error MSB4018: The "CreateTemplateTask" task failed unexpectedly.
1>C:\Git\ASP.NET-MVC-Boilerplate\Source\packages\TemplateBuilder.1.1.3\tools\ligershark.templates.targets(512,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Git\ASP.NET-MVC-Boilerplate\Source\packages\TemplateBuilder.1.1.3\tools\ligershark.templates.targets(512,5): error MSB4018:    at LigerShark.TemplateBuilder.Tasks.CreateTemplateTask.RecurseItems(XElement projectItemContainer, String sourcePrefix, String targetPrefix, HashSet`1 takenSourceFileNames, HashSet`1 takenTargetFileNames)
1>C:\Git\ASP.NET-MVC-Boilerplate\Source\packages\TemplateBuilder.1.1.3\tools\ligershark.templates.targets(512,5): error MSB4018:    at LigerShark.TemplateBuilder.Tasks.CreateTemplateTask.Execute()
1>C:\Git\ASP.NET-MVC-Boilerplate\Source\packages\TemplateBuilder.1.1.3\tools\ligershark.templates.targets(512,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Git\ASP.NET-MVC-Boilerplate\Source\packages\TemplateBuilder.1.1.3\tools\ligershark.templates.targets(512,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__1.MoveNext()
```

2 - The replacement method worked. It would be nice if this https://github.com/ligershark/side-waffle/issues/172 was implemented as I don't already have this feature.

**Comment by sayedihashimi** [comment]
@RehanSaeed I just tried it and it worked. The .zip file is at https://dl.dropboxusercontent.com/u/40134810/SideWaffle/issue-283/VSIXProject1.zip.

Here is the full snippet I added

```<ProjectItem ReplaceParameters="true" TargetFileName="readme.html" OpenInWebBrowser="true">readme.html</ProjectItem>```

FYI when debugging you can build the project and then look in the bin folder for the vsix and open it in a zip tool and inspect the .vstemplate file that is generated. That will give you an idea of how those items should be declared.

**Comment by RehanSaeed** [comment]
Thank you that worked! I was missing the TargetFilename attribute. I have now [switched](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate) to using SideWaffle.

I want to create a MVC 6 project template next. I see that there is a [workaround](https://github.com/ligershark/side-waffle/wiki/How-to-create-templates-for-ASP.NET-vNext) for this. I've followed the instructions but am currently getting the following errors:

```
Severity	Code	Description	Project	File	Line
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.gif" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.gif". Illegal characters in path.	Boilerplate.Vsix		
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.png" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.png". Illegal characters in path.	Boilerplate.Vsix		
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.jpg" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.jpg". Illegal characters in path.	Boilerplate.Vsix		
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.bmp" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.bmp". Illegal characters in path.	Boilerplate.Vsix		
```

You can do a Git clone of https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate to see my code.

**Comment by RehanSaeed** [comment]
@sayedihashimi Adding this line still seems to be causing errors intermittently. Even your sample project fails.

```
<ProjectItem ReplaceParameters="true" TargetFileName="ReadMe.html" OpenInWebBrowser="true">ReadMe.html</ProjectItem>
```

Most of the time I get two error dialog boxes below showing up with the messages below. The ReadMe.html file is missing from my VSIX file. Removing the above line solves the problem.

Dialog 1

> The file ReadMe.html could not be found within the project templates. Continuing to run, but the resulting project may not build properly.

Dialog 2

> Unable to copy the file 'ReadMe.html' from the project template to the project. Cannot find file "C:\Users\[Profile]\Rehan\AppData\Local\Temp\psckg2e.kxp\Temp\ReadMe.html".

I managed to get it to work last time but I don't know why it started working. I'm trying to do another release and am unable to get a VSIX with my ReadMe.html file in it. I have tried several variations but no success so far.

**Comment by sayedihashimi** [comment]
@RehanSaeed where is the project located? Is it https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate? If so I did the following.
 - Forked it to https://github.com/sayedihashimi/ASP.NET-MVC-Boilerplate
 - Updated to use the latest [prerlease of TemplateBuilder](https://github.com/sayedihashimi/ASP.NET-MVC-Boilerplate/commit/af3c2811473c223c8b1371ba026ed28cd882ed74) (as I mentioned on another thread)
 - Modified the solution build configuration to only build the vsix project

After building the vsix when I created a boilerplate project the readme was successfully shown in the VS browser. Can you give me some specific steps to follow?

**Comment by RehanSaeed** [comment]
I tried it on two machines, one was VS 2015 RC, the other was VS 2015 Pre-RTM and both had failed. I spent an hour messing around with different settings and couldn't figure out what was causing it.

I have since upgraded to [TemplateBuilder 1.1.4-beta](https://github.com/ligershark/side-waffle/issues/287) and it has started working again :+1:. I will keep an eye out for this bug.
