### ISSUE TITLE
AngularJS directive template usage comment not displaying proper values

### ISSUE THREAD

**Issue by kentcooper** [ligershark/side-waffle#285]
Not sure if we will be able to resolve it or not but in the directive template there is a usage example that when the $safeitemname$ is camel case the comment is not correct. For example when the directive name is directTest you end up with this:

      .directive('directiveTest', directiveTest);

        // Usage:
        //     <directiveTest></directiveTest>

when it should be:

       .directive('directiveTest', directiveTest);

        // Usage:
        //     <directive-test></directive-test>

Issue comes from https://visualstudiogallery.msdn.microsoft.com/a16c2d07-b2e1-4a25-87d9-194f04e7a698 QA section

**Comment by johnpapa** [comment]
ah. hmmm. is there a camelCaserizer ? :)

**Comment by johnpapa** [comment]
or a dasherizer?

**Comment by sayedihashimi** [comment]
I think we will need a custom wizard for this. If you can create a class to convert the strings I can help with the wizard part.

**Comment by johnpapa** [comment]
https://github.com/MehdiK/Humanizer#dasherize--hyphenate ?

**Comment by kentcooper** [comment]
@johnpapa that looks like its for _ to - we would need camelCase to dash right? I can write the class to do that part of it if we can't find one.

**Comment by johnpapa** [comment]
could be useful too.

**Comment by kentcooper** [comment]
true. Checked the directive snippet as well but that doesn't seem to include the actual usage so we should be good there.
