### ISSUE TITLE
ASP.NET 5 MVC 6 Project Template

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/side-waffle#287]
I want to create a MVC 6 project template. I see that there is a [workaround](https://github.com/ligershark/side-waffle/wiki/How-to-create-templates-for-ASP.NET-vNext) for this. You can do a Git clone of https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate to see my code. I've followed the instructions but am currently getting the following errors:

```
Severity	Code	Description	Project	File	Line
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.gif" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.gif". Illegal characters in path.	Boilerplate.Vsix		
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.png" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.png". Illegal characters in path.	Boilerplate.Vsix		
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.jpg" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.jpg". Illegal characters in path.	Boilerplate.Vsix		
Error		Unable to copy file "C:\Git\ASP.NET-MVC-Boilerplate\Source\MVC6\Boilerplate.Web.Mvc6.Sample\_Definitions\..\**\*.bmp" to "obj\Debug\ls-Templates\ProjectTemplate\Boilerplate.Web.Mvc6.Sample.project\**\*.bmp". Illegal characters in path.	Boilerplate.Vsix		
```

 Also, my VSIX installs to VS 2012 and above. Is it possible to restrict this template to VS 2015 only or will I have to create a separate VSIX for 2015 and above?

**Comment by sayedihashimi** [comment]
@RehanSaeed did you do anything special to get into this state or you just fell into it? For example did you modify any MSBuild targets or just took the defaults?

**Comment by RehanSaeed** [comment]
All I did was right click my VSIX project and click on 'Add template reference (SideWaffle project)' and then modify the _project.vstemplate.xml and _preprocess.xml files. I have not modified any MSBuild targets files.

**Comment by sayedihashimi** [comment]
This is the first that I'm seeing this error. I think it's related to a path too long exception when MSBuild is trying to expand the expression to find files to copy. I'll report back soon.

**Comment by sayedihashimi** [comment]
@RehanSaeed I deleted the ```node_modules``` and ```bower_components``` folders and the process completed successfully. I think we should do two things:

 - Try and use npm flatten folders package to reduce the overall path length
 - See if we can exclude ```node_modules``` and ```bower_components``` from the vsix creation process

I think it's safe to exclude ```node_modules``` and ```bower_components``` by default in the VSIX correct? If so I will go ahead and make the change and share it with you for testing.

**Comment by RehanSaeed** [comment]
[Flatten packages](https://www.npmjs.com/package/flatten-packages) might improve things a little and get things building but excluding node_modules and bower_components is the way to go. I suppose I could also manually delete these folders and build.

I have [this](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC6/Boilerplate.Web.Mvc6.Sample/wwwroot/.gitignore) .gitignore inside my wwwroot folder to stop files generated from my gulpfile.js from being checked in. Perhaps you could use a .gitignore file to determine what files to check in.

I'd be glad to test it.

**Comment by sayedihashimi** [comment]
@RehanSaeed ok I tried using `Exclude` to prevent `node_modules` and `bower_components` from causing issues with long paths. That didn't work out. I think I'll need to make bigger changes like using robocopy to copy the folder and exclude `node_modules` and `bower_components`.

**Comment by sayedihashimi** [comment]
@RehanSaeed I've made some changes in templatebulder https://github.com/ligershark/template-builder/commit/f67c6076c09a9d7c81017388a2e53ca2be150327 that should help in this case. I've released it to nuget.org as version `1.1.4-beta`. You can try out the fix with updating to that version of the nuget package with the command below `Install-Package TemplateBuilder -Version 1.1.4-beta -Prerelease`. Note: if you already have templatebuilder installed you may need to uninstall it, close VS and then install the version above.

**Comment by RehanSaeed** [comment]
1.1.4 beta has got rid of the errors. I cannot see the template appear in the 'New Project' dialogue though. Have I done something wrong in my SideWaffle xml? According to [this](https://github.com/ligershark/side-waffle/wiki/How-to-create-templates-for-ASP.NET-vNext) I just needed to set the project type to 'ProjectK'.

# _project.vstemplate.xml

```
<VSTemplate Version="3.0.0" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" Type="Project">
  <TemplateData>
    <Name>ASP.NET MVC 6 (Beta 5) Boilerplate (Also Beta)</Name>
    <Description>A professional ASP.NET MVC template for building secure, fast, robust and adaptable web applications or sites. It provides the minimum amount of code required on top of the default MVC template provided by Microsoft. Find out more at RehanSaeed.com</Description>
    <DefaultName>WebProject</DefaultName>
    <ProjectType>ProjectK</ProjectType>
    <ProjectSubType></ProjectSubType>
    <SortOrder>1000</SortOrder>
    <CreateNewFolder>true</CreateNewFolder>
    <ProvideDefaultName>true</ProvideDefaultName>
    <LocationField>Enabled</LocationField>
    <EnableLocationBrowseButton>true</EnableLocationBrowseButton>
    <Icon>sw-file-icon.png</Icon>
    <TemplateID>[MY GUID]</TemplateID>
    <NumberOfParentCategoriesToRollUp>1</NumberOfParentCategoriesToRollUp>
    <RequiredFrameworkVersion>4.5</RequiredFrameworkVersion>
  </TemplateData>
  <TemplateContent>
    <Project TargetFileName="Boilerplate.Web.Mvc6.Sample.xproj" File="Boilerplate.Web.Mvc6.Sample.xproj" ReplaceParameters="true">
      <ProjectItem ReplaceParameters="true" TargetFileName="ReadMe.html" OpenInWebBrowser="true">ReadMe.html</ProjectItem>
    </Project>
  </TemplateContent>
</VSTemplate>
```

# _preprocess.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<Preprocess>
  <!--
  You can specify the path where this should show up in the
  Add New Project / Add New Item dialog by setting the value below
  -->
  <TemplateInfo Path="CSharp\Web"/>
  <Replacements Include="*.*" Exclude="*.vstemplate;*.csproj;*.fsproj;*.vbproj;*.jpg;*.png;*.ico;_preprocess.xml;_project.vstemplate.xml">
    <add key="MvcBoilerplate" value="$safeprojectname$"/>
  </Replacements>
</Preprocess>
```

**Comment by sayedihashimi** [comment]
With VS2015 RTM try the following

```
<ProjectType>CSharp</ProjectType>
<ProjectSubType>Web</ProjectSubType>
```

**Comment by RehanSaeed** [comment]
I'm now on RTM. Adding the above gets me a little further. The project now appears in the 'New Project' dialogue. However, when I generate the project, it is completely empty except for the .xproj project file.

**Comment by sayedihashimi** [comment]
@rehansaeed did you get it figured out yet or still need some help here?

**Comment by RehanSaeed** [comment]
Still need some help. When I generate the project, it's completely empty.

**Comment by sayedihashimi** [comment]
Can you give me a link to the repo or email me the code?

**Comment by RehanSaeed** [comment]
https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate

**Comment by opoani** [comment]
Hi, Im experiencing a similar problem. Im trying to pack a 2015 MVC project and at first I also got the  "Illegal characters in path" but that got sorted out with the beta release. 

Unfortunately then i get the next error, and it might be related t some misconfiguration I have done but i don't have a clue ....here? 

I tried to follow the tutorials and it appeared pretty straight forward but i have sort of hit a brick wall here so any help would be appreciated 8-)     

System.UnauthorizedAccessException: Access to the path 'C:\AST\Base\MVC5_Full_Version\TemplatePackage\obj\Debug\ls-Templates\ProjectTemplate\Template.project\Template.csproj.vspscc' is denied.

Full trace in build output was:

1>C:\AST\Base\MVC5_Full_Version\packages\TemplateBuilder.1.1.4.0-beta\tools\ligershark.templates.targets(786,5): error : System.UnauthorizedAccessException: Access to the path 'C:\AST\Base\MVC5_Full_Version\TemplatePackage\obj\Debug\ls-Templates\ProjectTemplate\Template.project\Template.csproj.vspscc' is denied.
1>C:\AST\Base\MVC5_Full_Version\packages\TemplateBuilder.1.1.4.0-beta\tools\ligershark.templates.targets(786,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\AST\Base\MVC5_Full_Version\packages\TemplateBuilder.1.1.4.0-beta\tools\ligershark.templates.targets(786,5): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\AST\Base\MVC5_Full_Version\packages\TemplateBuilder.1.1.4.0-beta\tools\ligershark.templates.targets(786,5): error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
1>C:\AST\Base\MVC5_Full_Version\packages\TemplateBuilder.1.1.4.0-beta\tools\ligershark.templates.targets(786,5): error :    at LigerShark.TemplateBuilder.Tasks.RobustReplacer.ReplaceInFiles(String rootDir, String include, String exclude, IDictionary`2 replacements, StringBuilder logger)
1>C:\AST\Base\MVC5_Full_Version\packages\TemplateBuilder.1.1.4.0-beta\tools\ligershark.templates.targets(786,5): error :    at LigerShark.TemplateBuilder.Tasks.ReplaceInFiles.Execute()

**Comment by sayedihashimi** [comment]
@RehanSaeed @opoani thanks for the report. I noticed that it wasn't working as well and investigated it. The problem boils down to the fact that files are not listed in the `.xproj` file. Let me explain a bit of how templatebuilder processes the project templates.

When a project template is processed the project file (.xproj,.csproj,etc) are merged with the `_project.vstemplate.xml` file to generate the final `.vstemplate` file. The generated `.vstemplate` file should have one `ProjectItem` entry for each file that gets added. This happens in the [CreateTemplateTask](https://github.com/ligershark/template-builder/blob/master/src/LigerShark.TemplateBuilder.Tasks/CreateTemplateTask.cs) in the [template builder .targets file.](https://github.com/ligershark/template-builder/blob/master/tools/ligershark.templates.targets#L518). For `.xproj` since the project doesn't have any files is the resulting `.vstemplate` file has no files listed and when you invoke the template only the `.xproj` file is created.

I also noticed that you'll need to remove the `TargetFilename` attribute on the `Project` element ([example](https://github.com/ligershark/side-waffle/commit/8b131fffedfbd9f0e0ace1cdcc24028d42d89d3c#diff-ce5b88113f07fa0971e2211b197cba84L20)).

If your project template is only including a small number of files, it's possible to manually create the entries in the `_project.vstemplate.xml` file. If you have a large number of files it will be more difficult.

The proper fix here is to update the [CreateTemplateTask](https://github.com/ligershark/template-builder/blob/master/src/LigerShark.TemplateBuilder.Tasks/CreateTemplateTask.cs) so that for `.xproj` projects it merges file system content into the generated `_project.vstemplate.xml` file. I think this would be pretty straight forward to do, but not sure if I'll be able to get to it soon.

If someone is willing to help with that I can guide you and we can work on it together. Thoughts?

https://github.com/ligershark/side-waffle/tree/master/Project%20Templates/xUnitTestProject

**Comment by sayedihashimi** [comment]
FYI I have added a DNX project template for xunit, you can see the sources at https://github.com/ligershark/side-waffle/commits/master/Project%20Templates/xUnitTestProject

**Comment by RehanSaeed** [comment]
@sayedihashimi I've created a pull request (https://github.com/ligershark/template-builder/pull/74) to add this support into the template builder. The files are now added inside the VSIX.

However, when I generate a project from the template, I still get an empty project. What am I missing?

**Comment by gamicklisafisher** [comment]
For copying and deleting “Long Path Tool” software should be try, many articles refer this for such solutions.

**Comment by blink2linkme** [comment]
After choosing empty project template of ASPNET 5 Templates and adding gulpfile.js I am continuously getting error. Error is due to creation of multiple node_modules folder i.e. node_modules folder contains another node_modules folder within in and so on. It worked after I copied node_modules folder after copying from another project which was created by choosing basic template.
