### ISSUE TITLE
Project Template Logos

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/side-waffle#291]
I noticed looking at the new [xUnit](https://github.com/ligershark/side-waffle/tree/master/Project%20Templates/xUnitTestProject) project template that there is a PreviewImage logo you can add to the template. Here is an extract of the _project.vstemplate.xml file:

```
<VSTemplate>
  <TemplateData>
    <!-- Omitted -->
    <Icon>logo-64-transparent.png</Icon>
    <PreviewImage>logo-512-transparent.png</PreviewImage> 
  </TemplateData>
</VSTemplate>
```

The template also contains three images
- sw-file-icon.png (64 x 64)
- logo-64-transparent.png (64 x 64)
- logo-512-transparent.png (512 x 512)

Why is the sw-file-icon.png there when it is not used? Is the name of this file fixed? When I have other images in the project template for Icon and PreviewImage, they get output as part of the project. How can I stop this from happening?

**Comment by RehanSaeed** [comment]
Ok, looks like sw-file-icon.png is hard coded in [ligershark.templates.targets](https://github.com/ligershark/template-builder/blob/master/tools/ligershark.templates.targets#L503).

I've created [this](https://github.com/ligershark/template-builder/pull/75) pull request to add sw-file-previewimage.png to the ignored files list.

Is my pull request required? Is there a way to add to this list of ignored files?

**Comment by sayedihashimi** [comment]
@RehanSaeed I think we can close this after your changes at https://github.com/ligershark/template-builder/pull/77. Please reopen if we need to do more here.
