### ISSUE TITLE
Deploying other VS artifacts via sidewaffle

### ISSUE THREAD

**Issue by avishnyakov** [ligershark/side-waffle#292]
Is it possible to deploy other VS artifacts via sidewaffle? 

We can already push project and items templates along with the snippets, but what other others?
For instance, debugger visualizer or additionalmenu items and so on?

How is it aligned with sidewaffle?

**Comment by sayedihashimi** [comment]
@avishnyakov thanks for the questions.

SideWaffle/TemplateBuilder just build on top of the existing support in Visual Studio. When you create a vsix there are two project types you can use; VSIX Project and VS Package project. Use VSIX Project if you want to create a vsix with just templates. Use VS Package project to create a Visual Studio Package, which can contain both templates and other items like what you listed and others.

So to answer you question ***How is it aligned with sidewaffle?*** I would say 100%. Whatever you can do with a VS Package project today you can do when you use SideWaffle/TemplateBuilder take care of the template part.

**Comment by avishnyakov** [comment]
Many thanks, that makes sense.
