### ISSUE TITLE
Generating an ASP.NET 5 global.json

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/side-waffle#294]
When creating a new ASP.NET 5 project, a global.json file also gets generated under the 'Solution Items' folder. Is it possible to generate this file along with my project template?

Another issue with this file is that there is a projects setting which controls the folders that the solution is under e.g.

```
{
    "projects": [ "Source", "Tests" ],
    "sdk": {
        "version": "1.0.0-beta6",
        "runtime": "clr",
        "architecture": "x86"
    }
}
```

The above global.json says that there should be a 'Source' and 'Tests' folder. I'm not entirely certain what this is used for but it complicates generating this file.

**Comment by sayedihashimi** [comment]
Yeah this is tricky. I'd rather that we call into a wizard, or other code, that is exposed by the DNX project system.

@billheibert, we are creating templates for DNX and would like to support creating the `global.json` and `src` folders. Any ideas if we can call into the One ASP.NET wizard that handles this? If it's not possible today, can we enable it for the future?

**Comment by sayedihashimi** [comment]
@RehanSaeed FYI I created a new issue at https://github.com/aspnet/Tooling/issues/153 so that we can try and get the supported added.

**Comment by RehanSaeed** [comment]
Excellent, Thank You!

**Comment by RandomlyKnighted** [comment]
@RehanSaeed per the issue above it looks like the project.json file is going away. Because Microsoft is going away from it and there is no way to do it via their API's currently I'm going to go ahead and close this issue.
