### ISSUE TITLE
MVC5 Scaffold error when using T4 files

### ISSUE THREAD

**Issue by xfischer** [ligershark/side-waffle#300]
Hi,

I have added ASP.NET Scaffloding T4 files to my project (using Add New...).
I did not alter any file added, and when I try to add a new controller with EF, I have the following error message : 
![image](https://cloud.githubusercontent.com/assets/2776898/9618929/e809be4e-510a-11e5-8b79-b8fff9710705.png)

I have used SideWaffle to translate scaffolded views, but no luck ! Thanks !

**Comment by sayedihashimi** [comment]
@xfischer what version of VS (including vs update) are you using?

**Comment by xfischer** [comment]
This is the VS install I have : 
Microsoft Visual Studio Community 2013 Version 12.0.40629.00 Update 5
Microsoft .NET Framework Version 4.5.51209

When I copy the CodeTemplate files from VS folder to solution folder, it works. It seems that there are small differences between VS T4 files and the ones provider by SideWaffle.

**Comment by sayedihashimi** [comment]
@xfischer that's what I was thinking could be the issue. Could you send a PR with the new files? They go to https://github.com/ligershark/side-waffle/tree/master/TemplatePack/ItemTemplates/Web/ASP.NET/Custom%20T4%20Files.

**Comment by xfischer** [comment]
OK, done. Should this work with VS2013 prior to update 5 ?

**Comment by sayedihashimi** [comment]
@xfischer thanks, merged it. You can grab a copy for testing at https://ci.appveyor.com/api/buildjobs/9s75umkobve6r0k1/artifacts/TemplatePack.vsix. It will be included in the next release. Closing this now.

**Comment by xfischer** [comment]
Thanks. I have installed the vsix file, but it still doesn't work with the same error.
I have compared and the T4 files = the ones in my PR = the ones on my VS dir, unaltered.
Is there something missing (ie a link between the generator used by VS 2013 Update 5 and the T4 files) ?

**Comment by sayedihashimi** [comment]
@xfischer I just tried that build with VS2013 Update 4 and it worked. I'll install update 5 and then try again.

I wonder if this is an issue with localized builds? Do you have a machine configured with English that you could try with?

**Comment by xfischer** [comment]
Yes it worked. Thanks for the delay.

**Comment by RandomlyKnighted** [comment]
@xfischer did you do anything different to get it to work?
