### ISSUE TITLE
TypeScript Angular Templates prefix interface

### ISSUE THREAD

**Issue by StefanSchoof** [ligershark/side-waffle#303]
The TypeScript AngularJs Templates prefixes the interfaces with a "I" (see f.e. [controller.ts](https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/TypeScript/AngularJs/TypeScript%20Controller/controller.ts)). 
The [TypeScript Coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) states
> Do not use "I" as a prefix for interface names.

**Comment by RandomlyKnighted** [comment]
@kentcooper could you take a look at this?

**Comment by kentcooper** [comment]
Thank you for you feedback. That style guide is for contributing to TypeScript itself and is not a recommended usage for using TypeScript in your project.

**Comment by StefanSchoof** [comment]
The TypeScript team has put a clarification to this on the top Coding guidelines:
 > While these guidelines are mainly meant for contributors to the TypeScript project, certain suggestions apply as to how idiomatic TypeScript code should be written (e.g. the "Names" and "Style" sections)
