### ISSUE TITLE
Items not getting included in VSIX

### ISSUE THREAD

**Issue by BRM013** [ligershark/side-waffle#304]
I've been going round and round on this, creating new projects from scratch, tearing others apart, I'm at a loss to understand what is going on.
I created a project, added some Item Templates and Snippets and all was working fine.
I then renamed some files, added some more and all of a sudden I started 'losing' items.
For instance, I have an Item Template that was being deployed, then I modified its Definition file and now it doesn't appear. I've even undone the change but it still doesn't appear.
Same with my snippets. I renamed them, now they don't appear. I created a new one and it doesn't get added.
From what I can tell, it doesn't seem to be getting added to the VSIX package itself, but I could be wrong.
Any help would be great.

**Comment by sayedihashimi** [comment]
Double check that the TemplateBuilder NuGet package was installed into the vsix project. If it is can you paste in the build log?

**Comment by BRM013** [comment]
Yes, the package is installed. It was working, build, deploy. Then just some renaming and then it stops working.

Here's the build output:
1>------ Build started: Project: Zetta1SideWaffle, Configuration: Debug Any CPU ------
1>  Removing ItemTemplate and ProjectTemplate files from Compile list
1>  Looking for item and project templates
1>  Creating a zip file for each template
1>  Copying template files to the intermediate folder
1>  Expanding mytemplate.vstemplate files for multi-project templates
1>  Zetta1SideWaffle -> 
1>  Zetta1SideWaffle -> 
1>  Creating VSIX Container...
1>  Zetta1SideWaffle -> S:\Source\Brett\Sandpit\Zetta1SideWaffle\Zetta1SideWaffle\bin\Debug\Zetta1SideWaffle.vsix
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Also of note is the template-report.xml, all items, with their correct naming, appear in the report. I'd post the solution but I don't think you can do that here.

**Comment by sayedihashimi** [comment]
Ok double check that the value in _project.template.xml matches the file name of your .csproj file.
If that's not it can you upload to dropbox and share the sources in a .zip file?

**Comment by BRM013** [comment]
_project.template.xml? I don't have one of them. I haven't created any project templates yet, just Item Templates and Snippets.
Interestingly, I just looked in the obj/debug/Is-Templates folder, and it appears one of my templates, which has the same name as another template but in a different folder, is included in the same zip. I have an Item Template called "Module". One for normal AngularJS and one for TypeScript AngularJS. They have the same folder name but appear under different branches (JavaScript and TypeScript respectively). They do have different Names in the definition files, but only the TypeScript one appears in the obj/debug folders with the additional standard template JavaScript file from the other. I think that may be the problem with this Item Template.

However it doesn't explain anything to do with the snippets. 

I will look at uploading a zip file, and send a reference to it.

**Comment by BRM013** [comment]
Here is a link to my onedrive where I have placed the zip file.
Note, this zip was created before I fixed the Item Template issue above, but the snippets still don't show

https://onedrive.live.com/redir?resid=3922A5E3E2C93FE!28348&authkey=!ACketTdzGz4-meo&ithint=folder%2czip

**Comment by BRM013** [comment]
Again looking through the obj/debug output. The visxDeployedFileListAbsolute.txt file contains file references that may not be valid.

C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\Controller As.csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\ControllerWithView.csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\Directive (multiple).csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\Directive (single).csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\Filter (multiple).csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\Module.csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\Service.csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\ControllerAs.csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\\TemplateBuilder.dll
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\\extension.vsixmanifest
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Content\images\\ZETTA1_logo.png
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\ngfore.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\ngdefer.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\nghttp.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\ngtimeout.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\region.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\snippet1.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Snippets\JavaScript\ZETTA1\\z1switch.snippet
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\ModuleJS.csharp.zip
C:\Users\Brett.Morris\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\ZETTA 1\ZETTA 1 - SideWaffle\0.3\Output\ItemTemplates\CSharp\Web\ZETTA 1\ModuleTS.csharp.zip

All the snippet references contain double backslashes. I think that is invalid?

**Comment by RandomlyKnighted** [comment]
@BRM013 I was unable to replicate your results. However, I had to make a change in order to get the snippets to show up. For some reason it wasn't picking up on the snippets.pkgdef assets file. Once I reselected the file all the snippets started showing up again. 

The only thing I wasn't able to figure out was why you're templates are showing up under the `Web\My Custom Templates` node instead of the `Web\JavaScript` and `Web\TypeScript` nodes.

I checked and all the item templates are showing up as well. Using the link below you can download my version of your project.

https://drive.google.com/file/d/0BwBsvUOoWx9oX3F3QjlDZmhURU0/view?usp=sharing

Seeing that all the item templates and snippets are showing up I'm going to close this issue. Feel free to reopen if you continue to have issues.
