### ISSUE TITLE
Multiple snippets within one snippet file issue

### ISSUE THREAD

**Issue by avishnyakov** [ligershark/side-waffle#306]
Once snippet file has more than once snippet defined, the following exception comes out.
Just not too sure if that is intended behavior or VS limitation so that we have to split snippets as "file-for-every-snippet". What's the story behind that?

```
Error	1	The "GenerateTemplatePackReport" task failed unexpectedly.
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at LigerShark.TemplateBuilder.Tasks.SnippetInfo.BuildFromSnippetFile(String snippetFilePath)
   at LigerShark.TemplateBuilder.Tasks.GenerateTemplatePackReport.<>c__DisplayClass14.<GetAllSnippetInfo>b__12(String snippetFilePath)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at LigerShark.TemplateBuilder.Tasks.GenerateTemplatePackReport.GetAllSnippetInfo(IList`1 snippetFilePaths)
   at LigerShark.TemplateBuilder.Tasks.GenerateTemplatePackReport.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()	
```

**Comment by RandomlyKnighted** [comment]
Which snippet was you trying to use?

**Comment by avishnyakov** [comment]
Added 'snippets' folder under VSIX project, added a few folders and then *.snippet file.

The snipprt file has CodeSnippets and then CodeSnippet XML nodes, so once the file has only one CodeSnippet - all fine, once there are two CodeSnippet elements within CodeSnippets  node - all dies.

All setup like here - http://madskristensen.net/post/shipping-visual-studio-snippets-in-an-extension just as I said, tried to create more than one snippet with in *.snipprt file

![](http://madskristensen.net.m82.be/posts/files/4b974a32-d899-4074-8b44-310fe2893be4.png)

**Comment by RandomlyKnighted** [comment]
Do you mean that you're trying to create more than one snippet in the folder? Because each ```.snippet ```file is a single snippet.

**Comment by avishnyakov** [comment]
I mean one file, many snippet in the file.

Seems that snippet file can have more than one snippet according to its shema, can't it?
https://msdn.microsoft.com/en-us/library/ms171418.aspx#codesnippets

>> Optional element. Parent element for all code snippet data. There may  be zero or more CodeSnippet elements in a CodeSnippets element 

Meaning, one or more, I guess. So it comes as this:

```
<CodeSnippets
    xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
    <CodeSnippet Format="1.0.0">
        <Header>
            <Title></Title>
        </Header>
        <Snippet>
            <Code Language="">
                <![CDATA[  My Snippet 1 ]]>
            </Code>
        </Snippet>
    </CodeSnippet>
 <CodeSnippet Format="1.0.0">
        <Header>
            <Title></Title>
        </Header>
        <Snippet>
            <Code Language="">
                <![CDATA[  My Snippet 2 ]]>
            </Code>
        </Snippet>
    </CodeSnippet>
</CodeSnippets>
```

**Comment by RandomlyKnighted** [comment]
Based on that documentation it sounds like it should be supported yes. 

@sayedihashimi does SideWaffle do anything special in order to handle Snippets?

**Comment by avishnyakov** [comment]
Oh, thanks for understanding and patience @RandomlyKnighted 

The stacktrace suggest that it is a build task LigerShark.TemplateBuilder.Tasks.SnippetInfo and 'weird' System.Linq.Enumerable.SingleOrDefault call. Might be typo, donno, and should be FirstOrDefault..
```
Error   1   The "GenerateTemplatePackReport" task failed unexpectedly.
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at LigerShark.TemplateBuilder.Tasks.SnippetInfo.BuildFromSnippetFile(String snippetFilePath)
   at LigerShark.TemplateBuilder.Tasks.GenerateTemplatePackReport.<>c__DisplayClass14.<GetAllSnippetInfo>b__12(String snippetFilePath)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at LigerShark.TemplateBuilder.Tasks.GenerateTemplatePackReport.GetAllSnippetInfo(IList`1 snippetFilePaths)
   at LigerShark.TemplateBuilder.Tasks.GenerateTemplatePackReport.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() 
``

**Comment by RandomlyKnighted** [comment]
Thanks for providing the stack trace. 

The [MSDN documentation](https://msdn.microsoft.com/en-us/library/bb342451(v=vs.100).aspx) for that class shows that there is a SingleOrDefault method.

It looks like the issue you are having is occurring [here](https://github.com/ligershark/template-builder/blob/master/src/LigerShark.TemplateBuilder.Tasks/SnippetInfo.cs#L28). It looks like what's happening is the SingleorDefault is trying to return a single snippet from the file but it's finding more than one.

**Comment by sayedihashimi** [comment]
There is likely some bug in the [GenerateTemplatePackReport task](https://github.com/ligershark/template-builder/blob/master/src/LigerShark.TemplateBuilder.Tasks/GenerateTemplatePackReport.cs). I've never tried with a VSIX that just has snippets (i.e. no templates). For now you can disable this by adding the following into the `template-builder.props` file under `Properties`

```xml
<ls-GenerateTemplateReport>false</ls-GenerateTemplateReport>
```

I've been getting annoyed by the template report so I think I'll disable that by default (by defaulting `ls-GenerateTemplateReport` to false.

**Comment by RandomlyKnighted** [comment]
@avishnyakov did the workaround help solve your problem?

**Comment by avishnyakov** [comment]
Hey mate, thanks for follow up. Ended up with separate files. One file per snippet.

**Comment by RandomlyKnighted** [comment]
Alright, sorry that we weren't able to find a better solution for you. I'm going to go ahead and close this issue.
