### ISSUE TITLE
Remove the need for ls-NonFileTypes

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#318]
Currently we look through the project file to figure out what files need to be merged with the .vstemplate file. Many project files have items which do not point to files. The current design for this is that we have `ls-NonFileTypes` to figure out what items to ignore during the .csproj->.vstemplate merge. This has caused issues with new project types.

Instead of this, we should just check for the existence of the file on disk. If the file is not there issue a message and then just ignore it. Then we can just get rid of `ls-NonFileTypes`.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi since this is something that will need to be fixed in TemplateBuilder I've created an issue there so we have a record of it. In the mean time I'm going to close this one.
