### ISSUE TITLE
Unable to copy file illegal characters in path v1.3

### ISSUE THREAD

**Issue by MCKRUZ** [ligershark/side-waffle#319]
So I know there is already a closed issue on this but I'm getting the same result with the new version which supposedly has fixed the problem.

Here is my error
Unable to copy file "C:\TFS\Tallan.Mobile.Web\Momentum-Dev\Momentum.EnterpriseTemplate\Momentum.EnterpriseTemplate\_Definitions\..\**\*.gif" to "obj\Release\ls-Templates\ProjectTemplate\Momentum.EnterpriseTemplate.project\**\*.gif". Illegal characters in path.

It looks as though it's failing on the Copy SourceFiles line here
`
    <Copy SourceFiles="@(_ls-extraprojfiles)"
          DestinationFiles="@(_ls-extraprojfiles->'$(ls-DestTemplateOutputRoot)%(RecursiveDir)%(FileName)%(Extension)')"
          SkipUnchangedFiles="true">
      <Output TaskParameter ="CopiedFiles" ItemName="ls-temp-FilesCopied"/>
    </Copy>
`

**Comment by MCKRUZ** [comment]
no love?

**Comment by RandomlyKnighted** [comment]
@MCKRUZ is this same issue you mentioned at the end of #317?

**Comment by MCKRUZ** [comment]
Yes sir it is.

I tried updating to the new beta but now I’m getting this

Severity Code Description Project File Line Suppression State 
Error 
The "FilesExcludeRegex" parameter is not supported by the "CreateTemplateTask" task. Verify the parameter exists on the task, and it is a settable public instance property. TemplatePack 



Severity Code Description Project File Line Suppression State 
Error 
The "CreateTemplateTask" task could not be initialized with its input parameters. TemplatePack

**Comment by sayedihashimi** [comment]
@mckruz try this, add the following condition to that copy statement.

```
Condition=" '@(_ls-extraprojfiles)' != '' "
```

**Comment by sayedihashimi** [comment]
I actually removed that copy statement a few versions ago. Can you update to the latest NuGet package (prerelease) of TemplateBuilder and try again.

**Comment by MCKRUZ** [comment]
I already tried updating, I now have these errors

Severity Code Description Project File Line Suppression State
Error
The "FilesExcludeRegex" parameter is not supported by the "CreateTemplateTask" task. Verify the parameter exists on the task, and it is a settable public instance property. TemplatePack



Severity Code Description Project File Line Suppression State
Error
The "CreateTemplateTask" task could not be initialized with its input parameters. TemplatePack

**Comment by sayedihashimi** [comment]
You shouldn't be getting that. I'm using the ltest version here in SideWaffle. I just updated today. Can you send me a sample that has that error?

**Comment by MCKRUZ** [comment]
I killed my whole app and started over.  Seems to be working now.  Thanks!
