### ISSUE TITLE
ASP.NET MVC Empty Project Template Issue

### ISSUE THREAD

**Issue by blink2linkme** [ligershark/side-waffle#322]
After choosing empty project template of ASPNET 5 Templates and adding gulpfile.js I am continuously getting error. Error is due to creation of multiple node_modules folder i.e. node_modules folder contains another node_modules folder within in and so on. It worked after I copied node_modules folder after copying from another project which was created by choosing basic template.

**Comment by RandomlyKnighted** [comment]
Did you add the SideWaffle Gulp file or the Visual Studio 2015 Gulp file?

**Comment by blink2linkme** [comment]
I added visual studio Gulpfile.js from its template

**Comment by RandomlyKnighted** [comment]
That's not a SideWaffle template. The issue itself is with Visual Studio. Per your conversation with @shana in github/VisualStudio#160 I also think you should send feedback to Microsoft via the Visual Studio feedback reporter.

**Comment by blink2linkme** [comment]
Ok thank you!!
