### ISSUE TITLE
Web App - references missing 

### ISSUE THREAD

**Issue by Macca2424** [ligershark/side-waffle#323]
Hi, i have followed your video, which is great, i just have one issue, when launching the new project from the template all the references are missing, like "system", "system.web" etc, can you advise how to include these?

**Comment by RandomlyKnighted** [comment]
@Macca2424 Sorry for the delay. Can you link to an example where this his happening so that I can try and assist you further?

**Comment by Macca2424** [comment]
Hi thanks for the reply, you can download the template and builder project from the link below, if you open the NgageBase project, you will see in the references they are all missing when i "F5" and add a new template, i assume i need to include these somehow.

http://www.ngagecms.com/NgageBase.zip

**Comment by sayedihashimi** [comment]
@Macca2424 I've never seen this before. How did you create this project?

**Comment by Macca2424** [comment]
i just followed this https://www.youtube.com/watch?v=z33jOo75CH4

**Comment by Macca2424** [comment]
i am using Visual Studio 2015 pro

**Comment by RandomlyKnighted** [comment]
@Macca2424 just got a chance to take a look at this. The video you were going using as a reference is out of date. Can you try to recreate your template using [these instructions](https://github.com/ligershark/side-waffle/wiki/How-to-create-a-project-template).

**Comment by RandomlyKnighted** [comment]
Seeing as we have not heard back from the original poster I'm going to close this issue.

@Macca2424 if you are still experiencing this problem please feel free to reopen this issue and we'll be happy to revisit the problem.
