### ISSUE TITLE
Update wiki for multi projects

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#328]
We should update the wiki for multi project templates in the following way.

 - Update to instruct users to add telemetry settings. We should make it clear that this is only needed when contributing to SideWaffle and should not be used when creating your own template pack
 - Update to instruct users to create a single `_preprocess.xml` in the root which has replacement values for each project
 - Add a link to my sample multi project repo at https://github.com/sayedihashimi/multiprojtemplatedemo
 - Mention to not modify the `.props` file as previously instructed as it would have broken things

**Comment by RandomlyKnighted** [comment]
I've updated the [How to create a multi project template](https://github.com/ligershark/side-waffle/wiki/How-to-create-a-multi-project-template) wiki article. Please look it over and let me know if you see any issues with the updates i made.

I should also note that I didn't find any mention of the .props file so I left out the comment you made above.
