### ISSUE TITLE
Potential null ref (reported on the NuGet project)

### ISSUE THREAD

**Issue by yishaigalatzer** [ligershark/side-waffle#332]
When creating a AngularJS + WebAPI project

See https://github.com/NuGet/Home/issues/1572#issuecomment-168054308

**Comment by sayedihashimi** [comment]
Maybe the activity log svc is coming back null https://github.com/ligershark/side-waffle/blob/master/LigerShark.Templates/GoogleAnalyticsWizard.cs#L97

**Comment by RandomlyKnighted** [comment]
Closing this issue. Feel free to reopen if you continue to have problems.
