### ISSUE TITLE
Requesting guidance with Dynamic Item Templates

### ISSUE THREAD

**Issue by peterpde** [ligershark/side-waffle#334]
I could use a little help.  I am trying to take advantage of the new Dynamic Item Templates and have published an attempt at https://github.com/IIHS/aurelia-ts-templatepack, but they do not seem to be showing up in Visual Studio.  I am using VS 2015.  My settings for the Side Waffle extension looks like...

![2016-01-11_9-58-32](https://cloud.githubusercontent.com/assets/2745878/12236903/20bdfd44-b84a-11e5-890f-460e11b9a4e1.png)

I have rebuilt the templates and restarted Visual Studio as per the instructions in the wiki.  I feel as if I am missing a step.  Could anyone provide me some direction?  Thanks.

**Comment by RandomlyKnighted** [comment]
From a quick glance everything looks right. I'll try to take a look at it today and see if I can figure out what's going on.

**Comment by sayedihashimi** [comment]
They are there, but in the wrong node path. See 
![sw-01](https://cloud.githubusercontent.com/assets/1283154/12241854/8a546f86-b84a-11e5-91df-7f5ccef0058f.png)

**Comment by sayedihashimi** [comment]
See https://github.com/IIHS/aurelia-ts-templatepack/pull/1

**Comment by peterpde** [comment]
Great.  I will take a look.

**Comment by RandomlyKnighted** [comment]
@peterpde were you able to fix your problem?

**Comment by peterpde** [comment]
Yes.  Everything is working fine now.  I think I was dealing with a combination of what @sayedihashimi  addressed above as well as asp.net 5 custom properties not being present in one of my templates.  Everything is working well now.  Thanks.
