### ISSUE TITLE
Angular 2.0 Support

### ISSUE THREAD

**Issue by StephenErstad** [ligershark/side-waffle#337]
We are looking to start using an Angular 2.0 based SPA and are hoping to have standardization of style through tooling like we have for Ng 1.x using Sidewaffle.  

This would mean SideWaffle would potentially support our endeavor through a project template that setup the initial files needed to transpile TypeScript to the JavaScript files and the base folder structure.  Also having the initial testing framework setup would be helpful.

From there having templates for the individual file templates.

All of this adhering to at least the initial draft of the John Papa style guide for Ng 2 that I believe is coming.

**Comment by johnpapa** [comment]
For now I have templates for VS Code that can be used as a basis. These are in my github repos and in the VS Code marketplace

They will evolve as A2 nears release

**Comment by StephenErstad** [comment]
This is fantastic!  I appreciate giving us a way to move forward without the tooling support.

Is the plan to eventually support A2 in SideWaffle eventually or will that be rolled into a different extension?  

Either way is there some ETA (even if it is just a hope)?

**Comment by johnpapa** [comment]
Yes, A2 will be in Side Waffle.

If you'd like, feel free to grab those templates I wrote and start adding them. I'd be happy to help review them and update them as A2 syntax changes

**Comment by sayedihashimi** [comment]
Also adding @RandomlyKnighted and @kentcooper

**Comment by kentcooper** [comment]
Do we want to add some templates for the beta version? Was also thinking of doing a project template but thought we should wait for the final release.

**Comment by RandomlyKnighted** [comment]
I haven't seen Angular's road map but I read somewhere the other day that they've barely touched on the list of items they want to add before the next beta release. With that in mind, I don't see why we couldn't add templates for the current beta version then update them as each new release is made.

**Comment by StephenErstad** [comment]
My team would be happy to use the beta version with the new templates and provide real feedback if you end up adding them.

**Comment by kentcooper** [comment]
alright I'll go ahead and add a few of them.

**Comment by kentcooper** [comment]
@StephenErstad  okay I added a component and service template. I haven't seen a ton of "real world" Angular2 code out there so any feedback on how to make the templates better or different types of templates to add would be greatly appreciated.

**Comment by johnpapa** [comment]
I'll pull and look

**Comment by kentcooper** [comment]
Thanks to @johnpapa I also added the pipe template. The changes have been merged so you should see them in the next build. Once you start using them please give us any feedback you might have on what is missing or what we should change. Thanks.

**Comment by johnpapa** [comment]
looks good.

here are the vscode snippets, for future reference https://github.com/johnpapa/vscode-angular2-snippets

**Comment by StephenErstad** [comment]
@kentcooper How do I get the beta version to try the templates out?

**Comment by RandomlyKnighted** [comment]
@StephenErstad You can download and install it from [here](https://ci.appveyor.com/api/buildjobs/qyqsq1pg1u9wevss/artifacts/TemplatePack.vsix). Please keep in mind that this is not an official version that you are downloading. We've still a couple PRs to merge before we make our next release.

**Comment by StephenErstad** [comment]
Makes sense.  This will allow me to easily review and give feedback on the obvious next steps and further refinement.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted did the changes make it into the sidewaffle main branch?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi Yes they did.

**Comment by lucamorelli** [comment]
I've found some items templates. is it available or planned a project template for angular 2?

**Comment by RandomlyKnighted** [comment]
I believe the current plan is to wait until there are less moving parts in Angular 2 before adding a project template.
