### ISSUE TITLE
SideWaffle-ItemTemplate-Basic may need updating

### ISSUE THREAD

**Issue by kentcooper** [ligershark/side-waffle#339]
Do we need to update the "SideWaffle Item Template" template to include the new custom parameters and the analytics wizard?

**Comment by RandomlyKnighted** [comment]
It has them already.

[C# vstemplate file](https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/CSharp.vstemplate)

[VB vstemplate file](https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/VB.vstemplate)

**Comment by kentcooper** [comment]
Is that in the latest build? When I added the new Angular2 directives they were missing.

**Comment by RandomlyKnighted** [comment]
According to the file history the `$TemplateType` parameter was added back in mid December. So it's been there for a while.

I'm not sure if it's in the latest build or not seeing as we have two different version numbers at the moment.

**Comment by kentcooper** [comment]
Alright well since its there regardless of the build I'll close this.
