### ISSUE TITLE
Multi Project Template Building using VSIX with TemplateBuilder- Sample Project in 2015 Failed

### ISSUE THREAD

**Issue by sarchandra** [ligershark/side-waffle#341]
Hi

I have followed the example and created the sample project in VS2015. But it could not create the MultiProject. I have shared my code using GitHub. Please help where I am wrong.

https://github.com/sarchandra/VSIX-Template.git

I have few questions. 
1. Can we use sidewaffle to create multiproject. Many attempt I have tried, but nothing works. When I added the sidewaffle project template, it creates _Definition folder with _profile.vstemplate file along with _preprocess.xml. It looks easy to add these definition. But, How can it be linked in root.vstemplate
2. When I followed the given sample, It is not creating the multiproject template. 
My sample code can be accesses https://github.com/sarchandra/VSIX-Template.git

**Comment by RandomlyKnighted** [comment]
We've recently made changes to the process for creating multi project templates. I'm behind on updating the wiki. I'll see if I can make some time to update the instructions.

**Comment by sarchandra** [comment]
Thanks, I would appreciate if it can be as soon and wait for this update.

**Comment by RandomlyKnighted** [comment]
I've updated the wiki I'm just waiting on confirmation to make sure that I didn't miss of the new changes.

**Comment by sarchandra** [comment]
I have created multi project Template without TemplateBuilder
Reference GitHub : https://github.com/sarchandra/VSIX-Template.git
It works. Still waiting for with TemplateBuilder how to create one

**Comment by RandomlyKnighted** [comment]
Hi @sarchandra @sayedihashimi recently created a new easier way to create handle multi-project templates. You can check it out here: http://youtu.be/ysvTROB963k.

**Comment by RandomlyKnighted** [comment]
Since we have not heard back in a while I'm going to go ahead and close this issue. If you continue to have problems feel free to reopen and we'll be happy to help you further.
