### ISSUE TITLE
Multi-project template

### ISSUE THREAD

**Issue by mtranchi** [ligershark/side-waffle#342]
I followed the example and it worked, however, once I added a nuget package (Entity Framework) to the Specification class library, it won't create that, saying it can't find App.config in \AppData\Local\Temp\yada yada\Temp.
I've done many iterations trying to get this to work, and in one of them, I somehow got past the App.config issue, but then when creating a new multi-project and doing a package restore, it doesn't restore/install any of them. Is the issue with the hint path in Specification.csproj in that it should bounce up one more directory?
 <HintPath>..\packages\EntityFramework.6.1.3\lib\net45\EntityFramework.dll</HintPath>

I'm using VS 2015

Love sidewaffle, great tool, thank you guys for all your work.

**Comment by RandomlyKnighted** [comment]
Hi @mtranchi @sayedihashimi  recently created a new easier way to create handle multi-project templates. You can check it out here: http://youtu.be/ysvTROB963k.

**Comment by RandomlyKnighted** [comment]
Since we have not heard back in a while I'm going to go ahead and close this issue. If you continue to have problems feel free to reopen and we'll be happy to help you further.
