### ISSUE TITLE
Typo in _preprocess.xml

### ISSUE THREAD

**Issue by mtranchi** [ligershark/side-waffle#344]
I believe I just noticed a typo in the generated code for _preprocess.xml:

`<Replacements Include="*.*" Exclude="*.vstemplate;*.csproj*.jpg;*.png;*.ico;_preprocess.xml">`

Should there be a semi-colon after .csproj?

**Comment by RandomlyKnighted** [comment]
Which template did you find this in?

**Comment by sayedihashimi** [comment]
This was fixed recently in https://github.com/ligershark/side-waffle/pull/333
