### ISSUE TITLE
Comment out telemetry in templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#350]
I think we should put the `WizardExtension` in https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SW-ProjectVSTemplateFile/_project.vstemplate.xml and https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SW-ProjectVSTemplateFile/fsharp._project.vstemplate.xml in comments. Users who are creating templates outside of SideWaffle will not be able to run their templates because of this element. So we should uncomment when contributing to SideWaffle.

@RandomlyKnighted

**Comment by RandomlyKnighted** [comment]
Will commenting these out (or possibly removing them altogether) cause the Appveyor test to fail when someone submits a PR?

**Comment by sayedihashimi** [comment]
For SideWaffle for newly added templates, if they are not uncommented it will fail. That's the correct behavior because that build script is specific to this project.

**Comment by RandomlyKnighted** [comment]
Should this also be done for these files?

https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/CSharp.vstemplate

https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/VB.vstemplate

**Comment by RandomlyKnighted** [comment]
@sayedihashimi when I commented out the telemetry info I get a [failed Appveyor build](https://ci.appveyor.com/project/RandomlyKnighted/side-waffle/build/1.0.9).

**Comment by sayedihashimi** [comment]
@RandomlyKnighted 
>Should this also be done for these files?
https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/CSharp.vstemplate
https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SideWaffle-ItemTemplate-Basic/_Definitions/VB.vstemplate

No because those files are template files used for the SideWaffle item template itself. Having custom params there makes sense because that file is used in SideWaffle. The files that I mentioned updating are **template content*** files. When you use a template the file that is generated should not have the telemetry params enabled. That's why I linked to the above files to get fixed, they are content files, not definition files.
