### ISSUE TITLE
Update Appveyor tests to not validate SideWaffle template files

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#356]
As mentioned in #350 when you comment out the telemetry in the vstemplate files of the `SW-ProjectVSTemplateFile` project you get a failed Appveyor build. This can be corrected by doing the following:

 - [x] Comment out the telemetry lines as mentioned in #350 
 - [x] Update the validation script to not test the vstemplate files for the `SW-ProjectVSTemplateFile` project

Now the question I have is do we need to do replicate this for the other 3 SideWaffle Extensibility templates or do we only need to do it for this project?

cc: @sayedihashimi

**Comment by sayedihashimi** [comment]
>Now the question I have is do we need to do replicate this for the other 3 SideWaffle Extensibility templates or do we only need to do it for this project?

I just replied to https://github.com/ligershark/side-waffle/issues/350#issuecomment-194704773

> [ ] Update the validation script to not test the vstemplate files for the SW-ProjectVSTemplateFile project

I think I found the offending line https://github.com/ligershark/side-waffle/blob/master/build-main.ps1#L566.

If that's not it we can disable validation by passing `-disableTemplateValidation` in https://github.com/ligershark/side-waffle/blob/master/appveyor.ps1 whenever the build script is called.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi something I hadn't noticed until I made PR #358 is that this is also validating the vstemplate **content** files. So we should probably exclude them as well. What do you think?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi Is there a way that I can use the filter on this line https://github.com/ligershark/side-waffle/blob/master/build-main.ps1#L566 to exclude specific files or will we need to do it differently? I'd like to get this finished this week so we can release a new version this weekend.

**Comment by sayedihashimi** [comment]
I think we can delete the line that checks _project.vstemplate.xml and leave the line that checks .vstemplate.

**Comment by RandomlyKnighted** [comment]
Is that all that we would need to do?

**Comment by sayedihashimi** [comment]
Yeah i think so
