### ISSUE TITLE
Update publishing to the VSIX Gallery (Nightly Builds) to only occur on the master branch

### ISSUE THREAD

**Issue by RandomlyKnighted** [ligershark/side-waffle#357]
Pulled from my discussion with @sayedihashimi & @madskristensen on https://github.com/ligershark/SideWaffleWebsite/issues/15

Currently, we are using the release branch to publish to the Visual Studio Gallery and GitHub releases. With this in mind, seeing as the master branch is where most of our commits happen I believe that the VSIX Gallery should only pull this branch.

Unless I'm mistaken this should be as simple as adding an if statement around https://github.com/ligershark/side-waffle/blob/master/appveyor.ps1#L19 and utilizing the Appveyor `APPVEYOR_REPO_BRANCH` environment variable.

**Note:** To save anyone reading this some time reviewing the Appveyor documentation the description for the `APPVEYOR_REPO_BRANCH` environment variable says: `build branch. For Pull Request commits it is base branch PR is merging into;`

**Comment by sayedihashimi** [comment]
+1
