### ISSUE TITLE
Could not copy the file for every item in the project!

### ISSUE THREAD

**Issue by NimaTheCoder** [ligershark/side-waffle#363]
After 10 hours I'm still struggling to debug my template projects! I could't fix this one
Error		Could not copy the file "D:\WorkArea\Essential.Template\Essential.Template\ProjectTemplates\Essential\Framework\Models\ProductModel.cs" because it was not found.

There is a misting folder before \Models\ but I didn't find any problem according to document. Multi projects templates are too complicated and needs manual works!

**Comment by sayedihashimi** [comment]
We can't reproduce the issue with the info you provided. Can you share a sample?

**Comment by NimaTheCoder** [comment]
Thank you very much, Sayed 
Sample link: https://www.dropbox.com/s/un1mk9133nh5ktl/Essential.Template%20-%20Copy.rar?dl=0

**Comment by NimaTheCoder** [comment]
I found another thing! renaming "_project.vstemplate.xml" to ''MyTemplate.vstemplate" fix the problem! ALMOST!

**Comment by NimaTheCoder** [comment]
Can you share a working sample ? I think documents are outdated! and also tried this https://github.com/sayedihashimi/multiprojtemplatedemo but it does not work itself!

**Comment by RandomlyKnighted** [comment]
Hi @NimaTheCoder @sayedihashimi recently created a new easier way to create handle multi-project templates. You can check it out here: http://youtu.be/ysvTROB963k.

**Comment by RandomlyKnighted** [comment]
Since we have not heard back in a while I'm going to go ahead and close this issue. If you continue to have problems feel free to reopen and we'll be happy to help you further.
