### ISSUE TITLE
ASP.NET Core Angular TypeScript project template

### ISSUE THREAD

**Issue by cveld** [ligershark/side-waffle#367]
What would be the procedure to create an ASP.NET Core Angular TypeScript project?

**Comment by RandomlyKnighted** [comment]
@cveld are you wanting to create your own template pack or add the project to SideWaffle?

**Comment by RandomlyKnighted** [comment]
Closing due to no response from original poster. @cveld you're welcome to reopen this issue if you would like to continue the discussion.
