### ISSUE TITLE
Auto Updating Extensions in VS2015 Update 2 Not Working

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/side-waffle#369]
VS2015 Update 2 has the ability to auto update extensions. However, this does not seem to be enabled for my extension. VS shows the following message on the right hand side with a warning triangle:

![untitled](https://cloud.githubusercontent.com/assets/2270364/14409062/c2607450-ff04-11e5-948f-5e50f4b369af.png)

Any ideas what you need to do to get auto updating extensions to work?

**Comment by RandomlyKnighted** [comment]
Are you installing it from the Visual Studio Gallery?

**Comment by RehanSaeed** [comment]
Yes.

**Comment by RehanSaeed** [comment]
Yes

**Comment by RandomlyKnighted** [comment]
Odd, because that's auto updating extensions has been there since VS2015 was first released. If you go to `Tools -> Extensions and Updates -> Updates -> Visual Studio Gallery` does your extension show up in the list?

**Comment by RehanSaeed** [comment]
It's a VS 2015 Update 2 feature (See the [release notes](https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx)). Still getting this warning message.

**Comment by sayedihashimi** [comment]
If you email me details I will forward it. I'm guessing there is some component in your vsix blocking auto updates.

**Comment by RehanSaeed** [comment]
I emailed you the full details and screenshot.

**Comment by RehanSaeed** [comment]
It turns out, I had selected the VSIX to install for 'All Users'. If you do this, VS requires the VSIX to be signed. There are probably not many developers who share a single install of VS on a single machine, so the easiest fix is to uncheck the 'Install for All Users' option.

**Comment by sayedihashimi** [comment]
@RehanSaeed glad we figured it out.
