### ISSUE TITLE
Error in VS2015

### ISSUE THREAD

**Issue by sandipintellial** [ligershark/side-waffle#370]
I have followed video https://www.youtube.com/watch?v=z33jOo75CH4 
And, on running the template project, I am getting following error

_Error: this template attempted to load component assembly 'LigerShark.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. For more information on this problem and how to enable this template, please see documentation on Customizing Project Templates.
_
**I am using VS2015 Pro**

**Comment by poppertech** [comment]
I have the same problem but with Visual Studio 2013 Update 5 Ultimate Addition. The template project is an ASP.NET MVC 5 application built from the empty template. I have tried uninstalling and reinstalling the nuget package (both release and pre-release).  [I have also tried adding the following line to the manifest file](https://github.com/ligershark/side-waffle/issues/79):

`<Asset Type="Microsoft.VisualStudio.Assembly" d:Source="File" Path="TemplateBuilder.dll" AssemblyName="TemplateBuilder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />`

**Comment by luckybrowne** [comment]
I have the same problem as reported by **sandipintellia**l on 11 April.  I followed the exact same steps and got the same error and I'm using Visual Studio2015 pro  Update  3

**Comment by henrik-jensen** [comment]
As sandipintellial I followed the [video guide](https://www.youtube.com/watch?v=z33jOo75CH4).
Tried both TemplateBuilder.1.1.4.9-beta ( `Install-Package TemplateBuilder -pre`) and TemplateBuilder.1.1.3.
The template installs in the VS2015 exp instance but gives and error message when adding the new project:
```
Error: this template attempted to load component assembly 
'LigerShark.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
For more information on this problem and how to enable this template, please
see documentation on Customizing Project Templates.
```

System info:
TemplateBuilder.1.1.4.9-beta/TemplateBuilder.1.1.3
SideWaffle Template Pack 1.21.400
Microsoft Visual Studio Community 2015 Version 14.0.25425.01 Update 3
Microsoft .NET Framework Version 4.6.01038
Windows 10 Home 10.0.10586 Build 10586

**Comment by henrik-jensen** [comment]
**WTF**:
I kind of solved the problem but I really don't like the reason behind this!
In `_project.vstemplate.xml` TemplateBuilder adds this:
```
...
  </TemplateContent>
  <WizardExtension>
    <Assembly>LigerShark.Templates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</Assembly>
    <FullClassName>LigerShark.Templates.GoogleAnalyticsWizard</FullClassName>
  </WizardExtension>
</VSTemplate>
```
Commenting the `<WizardExtension>` out solves the problem but **why** did TemplateBuilder add **GoogleAnalyticsWizard** in the first place? I know the dll was not loaded, hence the error, but this kind of smells bad.

**Comment by RandomlyKnighted** [comment]
@henrik-jensen The GoogleAnalyticsWizard is how we, the SideWaffle dev team, keep track of which templates are being used and which are not. It helps us decide which ones we should updated and which ones should be retired from the extension. 

You were correct in commenting out the Wizard. I'll update the wiki article now.

**Comment by henrik-jensen** [comment]
@RandomlyKnighted
Well, it really needs to be mentioned very **loud** and **clear** and preferably be some kind of opt-in, though I would understand if this could be awkward to implement in this scenario. But maybe I should continue that part of the discussion over at #178 where it seems more appropriate.

re: Which template:
Was following the aforementioned [video tutorial](https://www.youtube.com/watch?v=z33jOo75CH4), which uses a classic csharp WinForms app as target template. I don't actually choose a template manually but this seems automated when adding a template reference to the WinForms app in the VSIXProject**<sup>1</sup>**. Couldn't find a "WinformApp" kind of template in the git-repo so I guess some generic type is chosen.

**<sup>1</sup>**. The tutorial by @sayedihashimi is of an older date using VS2013. In this he manually has to add a new item ->Extensibility->SideWaffle Project Template Files, this process now seems automated. Though there possibly are some bugs with the generated `_project.vstemplate.xml` where in the video the proper names (`WindowsFormsApplication1,csproj`)are generated while my generated files the names was replaced with `$rootnamespace$.csproj` which resulted in a build error of the VSIX project. I'll issue a bug report when I have investigated it further to see if it was not an error on my part.

ps. The Video tutorial is identical to the one presented in the wiki entries [How to create a project template](https://github.com/ligershark/side-waffle/wiki/How-to-create-a-project-template) and [How to create your own template pack](https://github.com/ligershark/side-waffle/wiki/How-to-create-your-own-template-pack)

**Comment by RandomlyKnighted** [comment]
That video is a bit outdated. As you mentioned we've automated some of the process. @sayedihashimi has actually be working to simplify the creation process even more. [This YouTube video is his most recent work]( https://youtu.be/ysvTROB963k) and is how we will be creating templates in the future.

**Comment by henrik-jensen** [comment]
>... simplify the creation process even more

Hmm?. I don't want to sound harsh here but if judged by the video I don't think it's quite there yet. I guess it's because of the preliminary nature of the pecan-waffle that it seems so complicated compared to the TemplateBuilder-SideWaffle combination video. There's a lot of manually editing source files, copying files from other folders, creating boilerplate templates and copying boilerplate code into these templates, finding guids and replacing them with other guids. But of course these processes will get automated I suppose.

**Comment by RandomlyKnighted** [comment]
You're welcome to provide feedback on pecan-waffle via it's [issue tracker](https://github.com/ligershark/pecan-waffle/issues). I'm sure @sayedihashimi would appreciate having another person to test it out and provide additional feedback. 

In the mean time, I've already created a Pull Request which once merged and released will give you the ability to opt-out of sending telemetry. I'm going to wait to update the wiki until after the next release. That way we're not providing instructions for something that hasn't released yet.

**Comment by henrik-jensen** [comment]
Thanks @RandomlyKnighted,
I'll dig more into pecan-waffle and templateBuilder and provide some feedback when I hopefully find the time next week. I'm especially interested in the possibilities of creating some C++ templates and, even though I know the SideWaffle tools have mostly been web oriented, I hope they can ease some of this as oppose to the buggy VS build-in Template Export Wizard.

**Comment by RandomlyKnighted** [comment]
@sandipintellial by following the solutions provided above you should be able fix your original issue. I'm going to go ahead and close this for now. If you continue to have problems please feel free to reopen the issue.

**Comment by sayedihashimi** [comment]
@henrik-jensen sorry about this. The problem here was that we have some tooling that adds the .vstemplate template file. The file that we used for that template had the wizard entry. That's only needed if people are submitting the templates to SideWaffle itself. So I've just commented that out in https://github.com/ligershark/side-waffle/commit/edda5d0ce0473204610b3c2bd1cbe0cd3e8d651f. The fix will be in the next release which I'm hoping to publish today. If you'd like to test you can grab the vsix from https://ci.appveyor.com/project/sayedihashimi/side-waffle/build/1.21.418/artifacts when the build finishes in a few minutes.
