### ISSUE TITLE
Visual Studio 2013 Crashes after installing Sidewaffle for web - version 1.21.400

### ISSUE THREAD

**Issue by subramn** [ligershark/side-waffle#373]
Hi,

I have installed the new version 1.21.400 and after the same Visual Studio 2013 with Update 5 is crashing.

Earlier version 1.20.339 works fine.

Can you please check

**Comment by RandomlyKnighted** [comment]
@sayedihashimi do you have VS2013 installed where you can test this out? All my computers are currently running 2015.

**Comment by subramn** [comment]
any way to fix this ? thanks for the great help

**Comment by sayedihashimi** [comment]
@subramn does version 1.20.339 works but 1.21.400 causes a crash? Or is the issue that VS Update caused something to break?

**Comment by subramn** [comment]
version 1.20.339 works but 1.21.400 causes a crash.

**Comment by sayedihashimi** [comment]
@subramn can you capture a crash dump so that I can analyze what the issue is? More info on dumps at https://blogs.msdn.microsoft.com/debugger/2009/12/30/what-is-a-dump-and-how-do-i-create-one/.

**Comment by RandomlyKnighted** [comment]
I'm going to close this due to no response. @subramn you are welcome to reopen it if you are still having this issue.
