### ISSUE TITLE
Possible to add a project template in two places?

### ISSUE THREAD

**Issue by RehanSaeed** [ligershark/side-waffle#381]
In ASP.NET Core RC2, web projects now appear in two places under 'Web' and '.NET Core'. Is it possible to do something similar? How would one achieve this?

**Comment by sayedihashimi** [comment]
@RehanSaeed you will need to copy the template .zip file into two different folders in the vsix under `output\projecttemplates`. I think you can do this with a custom build target that runs at the right time.

**Comment by RandomlyKnighted** [comment]
@RehanSaeed did this help you achieve what you were trying to do?

**Comment by RehanSaeed** [comment]
Haven't had a chance to look at this. Will do soon.
