### ISSUE TITLE
TemplateBuilder assembly removed form csproj file

### ISSUE THREAD

**Issue by shrey001** [ligershark/side-waffle#383]
I did everything I could to solve the problem as mention in issue #79 but the problem still remains can anyone tell me what I m doing wrong here

**Comment by RandomlyKnighted** [comment]
In order to make it clearer to know what's going on I've updated the issue title.

The error the OP was having is below:

```
Error: this template attempted to load component assembly 'TemplateBuilder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. For more information on this problem and how to enable this template, please see documentation on Customizing Project Templates
```

**Comment by RandomlyKnighted** [comment]
@shrey001 is this a multi project template?

**Comment by shrey001** [comment]
@RandomlyKnighted yes it is a multi project template.

**Comment by RandomlyKnighted** [comment]
@shrey001 Sorry for the delay. @sayedihashimi recently created a new easier way to create handle multi-project templates. You can check it out here: http://youtu.be/ysvTROB963k.
