### ISSUE TITLE
Self-hosting template missing

### ISSUE THREAD

**Issue by bluebaroncanada** [ligershark/side-waffle#386]
I see that there's no longer a self-hosting template.  The side-waffle page says it should be there.

Content
Project templates
..
Nancy empty self hosted
Nancy empty self hosted with razor
..
Nancy with self host
Nancy with self host with Razor

Using VS 2015

Even the demo video you have on the site shows exactly what I'm seeing and that does not include any self-hosting options

![image](https://cloud.githubusercontent.com/assets/5856849/17902148/19bcc0d4-6934-11e6-874b-e9ddfb2b1d85.png)

**Comment by bluebaroncanada** [comment]
Sorry to say, but I'm dead in the water here.  Critical!

**Comment by RandomlyKnighted** [comment]
@bluebaroncanada I'm sorry to say that this must have been removed some time ago. I've been a member of the SideWaffle Core Dev Team for over a year now and in that time we have not added but not removed templates from SideWaffle. 

@sayedihashimi do you know when this was removed or have any advice for @bluebaroncanada

**Comment by RandomlyKnighted** [comment]
@bluebaroncanada I stand corrected. I just found the self-hosted templates. I found them by going to `File =>New Project` and then you find them under `Visual C# => Windows => SideWaffle`. There are 4 self-hosted templates that you can use.

**Comment by bluebaroncanada** [comment]
Ahhh!  Thanks!
