### ISSUE TITLE
Project template for asynchronous console app missing?

### ISSUE THREAD

**Issue by AndreArtus** [ligershark/side-waffle#387]
SideWaffle used to have a template for creating asynchronous console application, that seems to have been removed in the latest version. I tried several reinstalls thinking that something must have gone wrong, but no luck.

Has it been removed?
If so then for what reason?
Is there a way I can get it back, without making my own (easy enough, but not fond of wheel reinvention)?

**Comment by RandomlyKnighted** [comment]
Hi @AndreArtus thank you for reporting this issue. The template has not been removed. It is still in the repo as [seen here](https://github.com/ligershark/side-waffle/tree/master/project-templates/Windows%20Desktop/ConsoleApplicationAsync). However, for some reason it's not getting bundle into the extension. I'll take a look at it and see if I can't get it fixed.

**Comment by RandomlyKnighted** [comment]
I'm going to go ahead and close this. The template has been added and will be included in the next release.
