### ISSUE TITLE
Create file next to *.sln

### ISSUE THREAD

**Issue by bednart** [ligershark/side-waffle#391]
Hi,
I want to create new project template and I would like to know if it's possible to create project template which if used creates file next to solution file. I am talking about .tfignore file exactly.

Thanks in advice,
Tomáš

**Comment by sayedihashimi** [comment]
To do that correctly I think you will need a custom wizard

**Comment by bednart** [comment]
I will try it, thanks ;)

**Comment by bednart** [comment]
Custom wizard works great :) Thanks for tip ;)
