### ISSUE TITLE
Template with multi projects

### ISSUE THREAD

**Issue by NgageSoftware** [ligershark/side-waffle#393]
Hi, i am trying to create a SideWaffle template which includes the output below, but i cannot get the second project to move across in the template.

Any ideas how this can be achieved?

VS Solution = $projectname$
- VS Project = BaseProject
- VS Project = $projectname$ with reference to BaseProject

**Comment by RandomlyKnighted** [comment]
@sayedihashimi can you answer this question? I still haven't been successful with Multi Project templates so I'm not sure how to fix this.

**Comment by sayedihashimi** [comment]
Multi-project templates are tricky but I've created a new template system which makes it easier. Take a look at my video http://youtu.be/ysvTROB963k and related comment https://github.com/ligershark/side-waffle/issues/393#issuecomment-254201896.

I'm going to close this because I think pecan-waffle has all the features needed. If you run into issues please reopen with details.

**Comment by NgageSoftware** [comment]
Hi Sayed,

That has worked very well, just one question...
How do i include the template icon, i have tried changing the icon node in vstemplate, but the icon or image does not get included in the template.

Many thanks

**Comment by sayedihashimi** [comment]
Hi @NgageSoftware in pecanwaffle I haven't wired up icons yet, but you can embed the icon in the vsix as a resource and then in the .vstemplate file you reference that. This is a feature of .vstemplate itself. I'm not sure exactly how to do that but I found a sample here on github. Take a look at the repo at https://github.com/borota/JTVS. More specifically take a look at the following two files:

 1. [class.vstemplate](https://github.com/borota/JTVS/blob/040de81096bbf09fa85d1c99c6b465619000c0cf/Src/Product/J/JTools/Templates/Files/PyClass/class.vstemplate#L5)
 1. [VSPackage.resx](https://github.com/borota/JTVS/blob/040de81096bbf09fa85d1c99c6b465619000c0cf/Src/Product/J/JTools/VSPackage.resx#L184)

You'll also have to add the image file to the vsix project, mark it as an embedded resource.

If you're able to figure out how to get the icons wired up from a resource I would really appreciate if you added a wiki entry to https://github.com/ligershark/side-waffle/wiki.

In addition to this

**Comment by NgageSoftware** [comment]
Hi Sayed,

Having one more issue, which i have tried various fixes found on google, do you know why i am getting this?

The VSIX installs fine on my machine, when i deploy the file to another machine, i get the error below.

PathTooLongExecption

i have uploaded the VSIX - http://assets.ngagecms.com/download/test.vsix
