### ISSUE TITLE
How to preserve the folder structure?

### ISSUE THREAD

**Issue by mahima-gopalakrishnan** [ligershark/side-waffle#396]
I hope this is not an issue and only needs a minor correction in the templates.

====================Update to my question to add more clarity==============
I have a template where I have grouped my source code projects under "src" folder and unit test projects under "test" folder in the file system. So my folder structure in the file system looks like this:

Definitions
|__CSharp.vstemplate
src
|__ABC
|______ABC.csproj, ABC_preprocess.xml, MyTemplate.vstemplate
|__XYZ
|______XYZ.csproj, XYZ_preprocess.xml, MyTemplate.vstemplate
test
|__ABCTest
|_____ABCTest.csproj, ABCTest_preprocess.xml, MyTemplate.vstemplate
|__XYZTest
|_____XYZTest.csproj, XYZTest_preprocess.xml, MyTemplate.vstemplate

I am able to successfully template them. When I create a solution from this multi-project template, the "src" and "test" folders are missing in the file system. So the project folders ABC, XYZ, ABCTest and XYZTest are all at the same level. So my folder structure looks like this:

Definitions
|__CSharp.vstemplate
ABC
|__ABC.csproj, ABC_preprocess.xml, MyTemplate.vstemplate
XYZ
|__XYZ.csproj, XYZ_preprocess.xml, MyTemplate.vstemplate
ABCTest
|__ABCTest.csproj, ABCTest_preprocess.xml, MyTemplate.vstemplate
XYZTest
|__XYZTest.csproj, XYZTest_preprocess.xml, MyTemplate.vstemplate

The VS solution folders are created successfully. No problem there. 

Where am I going wrong? Any help is appreciated.

**Comment by Sakuto** [comment]
Encountering the same issue, have you found something?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi can you help answer this one?

**Comment by sayedihashimi** [comment]
In VS the `src` and `test` folders are "solution folders". TemplateBuilder leverages the existing VS template support for the actual template. As far as I know it's not possible out of the box to create solution folders with a `.vstemplate`. You could support this by creating a custom wizard though. I think the custom wizard could be implemented like:
 - run after the project is created
 - create if needed the `src` (or `test` depending on path) solution folder
 - remove project from the solution
 - add project to the `src` (or `test`) solution folder

**Comment by Sakuto** [comment]
@sayedihashimi I'll go for this solution, many thanks for your support!

**Comment by RandomlyKnighted** [comment]
@mahima-gopalakrishnan have you tried the solution listed above?

**Comment by mahima-gopalakrishnan** [comment]
@sayedihashimi "src" and "test" are not solution folders. Actually I'm able to successfully create VS solution folders to group my projects. 
![vs_sln_folders](https://cloud.githubusercontent.com/assets/24846567/21770204/3c0614b8-d650-11e6-9ecc-4fa58a061baf.png)
In the file system, I'd like the projects under the "Apis", "Business" and "Data" solution folders to be created under "src" because they are source code. I'd like the projects under "Tests" solution folder to be under "tests" folder in the file system.

**Comment by sayedihashimi** [comment]
@mahima-gopalakrishnan the nodes in VS where you see "Apis", "Business", etc are referred to as "Solution Folders".

**Comment by mahima-gopalakrishnan** [comment]
@sayedihashimi True. Apis, Business etc are solution folders. I'm able to successfully create those folders through the template. I was asking about the "src" and "tests" folders which are file system folders.

![file_sys_folders](https://cloud.githubusercontent.com/assets/24846567/21823666/23d0cd16-d74a-11e6-9fcd-368d29e655ce.png)

**Comment by mahima-gopalakrishnan** [comment]
Looks like custom wizard is the only option. Closing the issue.
