### ISSUE TITLE
How to replace the name of a file when creating a template?

### ISSUE THREAD

**Issue by 1TheMuffinMan** [ligershark/side-waffle#398]
Using TemplateBuilder and the example project that creates two projects from a template I was wondering if there was a way to change the name of a file itself using `$saferootprojectname$`?

Here's my the main template project with the .vstemplate open for the particular project I want to change the file name in. You'll notice that I added a `ProjectItem` under the Project, which seems to be the way to accomplish this, however it keeps telling me it can't find the file.

![example 1](https://cloud.githubusercontent.com/assets/4889283/22255584/a1557dfa-e20c-11e6-88d1-b1efe13058cc.PNG)

Here's an image of the project template to show the structure:
![example 2](https://cloud.githubusercontent.com/assets/4889283/22255653/d6330fd8-e20c-11e6-909b-3a470ec0bfc2.PNG)

**Comment by sayedihashimi** [comment]
That looks like it should work. That said multi-project template can be very tricky. There is a new way to build multl project templates which is covered at https://youtu.be/ysvTROB963k. I think creating your multi project template with this new approach will be much easier.
With that said I'm working with my team at Microsoft on the [Template Engine](https://github.com/dotnet/templating/). We don't have support to create templates for VS yet but we will in a few months. After that happens I'll re-direct you to create your template with that new approach, and that should stick for the long term.

**Comment by 1TheMuffinMan** [comment]
@sayedihashimi Awesome news about the template engine. I'll close this and keep an eye on it.
