### ISSUE TITLE
Question: Create Solution folder and add projects when creating from template

### ISSUE THREAD

**Issue by aagarwal10** [ligershark/side-waffle#406]
Hi, 

I m using VS 2017 Update 3 with .NET Core 2.0 

I have a template project that is able to create a solution with following projects

Example: 
Abhishek.Component.sln
           Abhishek.Component.Entities
           Abhishek.Component.Extensions
           Abhishek.Component.Abstractions
           Abhishek.Component.UnitTests
           Abhishek.Component.IntegrationTests

However I want to have a solution folder that will group my test projects like this in a project created from template automatically;

Abhishek.Component.sln
           Abhishek.Component.Entities
           Abhishek.Component.Extensions
           Abhishek.Component.Abstractions
           Tests
                  Abhishek.Component.UnitTests
                  Abhishek.Component.IntegrationTests

-----------------------------

Is it possible to have this structure automatically created when a project is created from template.

Any help is appreciated

--Abhishek

**Comment by sayedihashimi** [comment]
Solution folders require you to create a custom VS wizard.

**Comment by aagarwal10** [comment]
Cool, thanks
