### ISSUE TITLE
When new solution is created, it creates an extra folder level for the projects inside the solution folder, so original internal dll references are broken(not nuget) 

### ISSUE THREAD

**Issue by barisgul** [ligershark/side-waffle#408]
Hi Sayed,
References are broken when create project from template. The broken references are because when new solution is created, it creates an extra folder level for the projects inside the solution folder. This breaks the original reference to the packages folder which is supossed to be one level above project files and now is 2 levels above. 
mention about this problem is here: https://blog.jayway.com/2015/03/13/visual-studio-how-to-create-a-solution-template-with-multiple-projects/

**Comment by barisgul** [comment]
Hi everyone, 
I solved this problem by modifying MyTemplate.vstemplate file. In file, I have changed to false from true CreateNewFolder attribute as below. This modification worked for me :) 
`<CreateNewFolder>false</CreateNewFolder>`

**Comment by tylerbhughes** [comment]
Thanks for sharing your solution @barisgul.

**Comment by berkaykirmizioglu** [comment]
Thanks for solution @barisgul, that worked for me.
