### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by MagB168** [ligershark/side-waffle#414]
Could you please add support new version of Visual Studio 2019? and please provide the download link at least for the QuickFix VS2019 (similar to QuickFix VS2017).
Thank you in advance.

**Comment by sayedihashimi** [comment]
I updated it a couple hours back. Can you try again?

**Comment by MagB168** [comment]
Ok it works. Thx.

**Comment by sayedihashimi** [comment]
Great, thanks.
