### ISSUE TITLE
Error after upgrading to v1.1

### ISSUE THREAD

**Issue by abmadmin1** [ligershark/side-waffle#416]
I get an error starting VS 2017 Community Edition after upgrading to SideWaffle.Creator v1.1. ActivityLog.xml is attached.

[ActivityLog.zip](https://github.com/ligershark/side-waffle/files/3606008/ActivityLog.zip)

**Comment by codewithtyler** [comment]
Good morning @abmadmin1 can you post this over in the [SideWaffle Creator](https://github.com/ligershark/sidewafflev2) repo please? This repo is for the older SideWaffle extension.
