### ISSUE TITLE
Update images in Wiki for multi-project template

### ISSUE THREAD

**Issue by alelom** [ligershark/side-waffle#418]
Following photobucket update on its policy (beginning of 2019) all pictures have become blurred and with watermark in the wiki:
https://github.com/ligershark/side-waffle/wiki/How-to-create-a-multi-project-template

please update the wiki with the images.

**Comment by codewithtyler** [comment]
Thank you for informing us of the policy update. I'm going to close this as a duplicate since this was previously reported in #417
