### ISSUE TITLE
Basic Scaffolder

### ISSUE THREAD

**Issue by DunnJM** [ligershark/side-waffle#419]
Hi,

I can't seem to find any information on how to build a scaffolder for Visual Studio 2019.

Is there a template like the Basic Scaffolder provided in this pack that would work for 2019, or any resources that I can use to start?

Thanks!

**Comment by sayedihashimi** [comment]
Thanks for the question. I'm not up to date on how to create a new scaffolder. I believe you reached out to me/Mads on twitter and we pointed you to Vijay https://twitter.com/sayedihashimi/status/1240283547858096132?s=20.
