### ISSUE TITLE
Add VsixCompress

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#59]
The .zip file is getting a little big. I tried VsixCompress a while back and it seemed to make the .zip file smaller. We should try again and then add it if the resulting .zip file is smaller.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi did you do this for the current release?

**Comment by RandomlyKnighted** [comment]
Once we've fully implemented the dynamic templates feature, will this still be necessary?

**Comment by RandomlyKnighted** [comment]
Per previous discussion, since the templates are already in .zip files it looks like VsixCompress won't help much with decreasing the size of the VSIX.
