### ISSUE TITLE
Item templates not available in nodejs projects

### ISSUE THREAD

**Issue by aschulz01** [ligershark/side-waffle#77]
Currently the side-waffle item templates are not available in Visual Studio node.js Projects. (Project file Extension .njsproj)

see http://nodejstools.codeplex.com/

Is it possible to support this project type as well?

&lt;ProjectTypeGuids&gt;
     {3AF33F2E-1136-4D97-BBB7-1795711AC8B8};
     {349c5851-65df-11da-9384-00065b846f21};
     {9092AA53-FB77-4645-B42D-1CCCA6BD08BD}
&lt;/ProjectTypeGuids&gt;

**Comment by amit-srivastava-007** [comment]
Well NodeJs project templates display under separate list named Node.Js Items which is default from Microsoft and hence no side-waffle templates visible inside this as Node.Js is the only node display in Add Item Window. I think a minimal changes can be made in next build to made these template available for .njsproj. This will be useful
