### ISSUE TITLE
MultiProj - Visual Studio Error

### ISSUE THREAD

**Issue by jsheldon** [ligershark/side-waffle#79]
When attempting to create a new project from the MultiProj template I get an error in visual studio:

Error: this template attempted to load component assembly 'TemplateBuilder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. For more information on this problem and how to enable this template, please see documentation on Customizing Project Templates.

I've checked the documentation at:
http://msdn.microsoft.com/en-us/library/dd631936.aspx

But have found nothing.

**Comment by bogacg** [comment]
I just had same issue (on Visual Studio 2015 Community) Sandboxed VS instance gets executed after Ctrl+F5, but when I want to create template it gives error above. I've manually added Asset tag to manifest file of VSIX project as well. TemplateBuilder.dll is placed in Debug folder of VSIX project.

**Comment by RandomlyKnighted** [comment]
@bogacg can you create a new issue explaining what happened and reference this issue? That way we can track how many people are having issues better.

**Comment by shrey001** [comment]
I m having the same issue #163 I did everything I could to resolve the issue but the problem still remains the same.
